README.md
Fixes https://github.com/GoogleCloudPlatform/open-match/issues/1 and another minor typo
=> fix typo in intro paragraph, and broken youtube link

internal/statestorage/redis/playerq/playerq.go
Yet another attempt to get my commit authorship accepted by the Google Cloud CLA.
Add timestamp indexing and de-indexing as a first class index for all match requests.
To use the timestamp index, match functions can us `ZRANGE` now to better segment filters. The short-term goal is to allow for the simplest way to run the same function multiple times at once.
I didn't debate the name too long, so we can come up with something more descriptive if there are good ideas. I didn't think starttime, qtime, createddate or any of the other db-toned names fit once you move into the match function context.
=> Timestamp Indexing

internal/statestorage/redis/redispb/matchobject.go
This fixes https://github.com/GoogleCloudPlatform/open-match/issues/51
=> Fix parsing of empty matchobject fields

examples/functions/python3/mmlogic-simple/harness.py, examples/functions/python3/mmlogic-simple/mmf.py
=> check for empty pools in py3 mmf

cmd/mmlogicapi/apisrv/apisrv.go
=> Off-by-one error in MMLogic API GetPlayerPools

internal/set/set.go, internal/set/set_test.go
This fixes #66.
Requires following docker images to be re-built:
- base
- cmd/mmlogicapi
- examples/functions/golang/manual-simple
=> fixed set.Difference()

internal/logging/helper.go
Simply set format in config to "stackdriver"
This uses github.com/TV4/logrus-stackdriver-formatter
=> Stackdriver logging format

internal/statestorage/redis/ignorelist/ignorelist_test.go, test/cmd/frontendclient/main.go
Fixing the build, vet, fmt errors in open-match.
=> Fix build and test breakages

cmd/frontendapi/apisrv/apisrv.go
=> remove player from ignorelists on frontend.DeletePlayer call

.gcloudignore, cloudbuild.yaml, internal/app/backendapi/backendapi.go, internal/app/frontendapi/frontendapi.go
Add presubmit checks for all the go code in open-match.
Addresses: https://github.com/GoogleCloudPlatform/open-match/issues/94
There's a few issues here:
* No docker image building (comes later)
* go mod artifacts are not being cached for some reason, https://github.com/GoogleCloudPlatform/cloud-builders/issues/468.
=> Initial cloudbuild.yaml script

config/config.go, config/matchmaker_config.yaml, examples/evaluators/golang/simple/Dockerfile, examples/evaluators/golang/simple/main.go, examples/functions/golang/manual-simple/Dockerfile, examples/functions/golang/manual-simple/main.go, examples/functions/golang/manual-simple/matchmaker_config.yaml, install/yaml/01-redis-failover.yaml, install/yaml/01-redis.yaml, install/yaml/02-open-match.yaml, internal/app/mmforc/mmforc.go, internal/statestorage/redis/redishelpers.go
Continued work on #42.
This is makes it possible to enable "requirepass" feature in single node Redis deployment and keep password in k8s Secret.
=> Redis authentication

Makefile, cloudbuild.yaml, config/matchmaker_config.yaml, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backendapi.yaml, install/helm/open-match/templates/frontendapi.yaml, install/helm/open-match/templates/grafana-dashboards.yaml, install/helm/open-match/templates/mmforc.yaml, install/helm/open-match/templates/mmlogicapi.yaml, install/helm/open-match/templates/om-configmap.yaml, install/helm/open-match/templates/service-account.yaml, install/helm/open-match/values.yaml, install/yaml/01-redis-chart.yaml, install/yaml/01-redis-failover.yaml, install/yaml/01-redis-simple.yaml, install/yaml/02-open-match.yaml, install/yaml/03-prometheus-chart.yaml, install/yaml/04-grafana-chart.yaml
Trying to minimize the number of k8s files that are created manually.
=> Generate install/yaml/ files from Helm chart templates

cloudbuild.yaml
=> Disable 'Lint: Kubernetes Configs'

doc.go
Creating an index package for godoc.
See https://github.com/GoogleCloudPlatform/open-match/issues/114 and https://github.com/GoogleCloudPlatform/open-match/issues/127.
=> Add base package file for godoc index and go get.

examples/functions/python3/mmlogic-simple/Dockerfile, examples/functions/python3/mmlogic-simple/harness.py
This fixes py3 MMF example which was not updated after https://github.com/GoogleCloudPlatform/open-match/commit/8db062f7b9e09eb09bfdad3e32e7c6b23d285356
=> Update py3 MMF example to use Request/Response protos

Makefile
=> Detect sudo invocations of Makefile #164

Makefile, README.md, install/yaml/01-redis-chart.yaml, install/yaml/02-open-match.yaml, install/yaml/03-prometheus-chart.yaml, install/yaml/04-grafana-chart.yaml, install/yaml/install-example.yaml, install/yaml/install.yaml
https://github.com/GoogleCloudPlatform/open-match/issues/161
=> Update install yaml files

internal/app/evaluator/harness.go
Error regression from changes in the previous commits.
=> fix for evaluator error

Makefile, cloudbuild.yaml, install/helm/open-match-example/Chart.yaml, install/helm/open-match/Chart.yaml, install/helm/open-match/values.yaml
Introduce golintci tool (not used yet because of a bug).
Add logo for Helm chart.
Consolidate all linters to run in the same GCB target.
=> Fix lint issues in helm chart and improve lint coverage.

Makefile
https://github.com/GoogleCloudPlatform/open-match/issues/262
=> make clean now deletes build/ (#262)

README.md
I created this PR against the release branch, but if it makes more sense to do it against master and cherry pick into the release branch let me know.
=> Fix grammer in the open match demo script.

Makefile
=> Fix the trailing slash issue in Makefile

.golangci.yaml, internal/future/serving/insecure.go, internal/future/serving/insecure_test.go, internal/future/serving/server.go
As part of the 0.6.0 partial rewrite we'll be introducing a new to create gRPC with proxy servers.
=> Add insecure gRPC serving to future/.

Makefile, README.md, cloudbuild.yaml, cmd/backendapi/Dockerfile, cmd/frontendapi/Dockerfile, cmd/mmlogicapi/Dockerfile, install/helm/open-match-example/Chart.yaml, install/helm/open-match-example/values.yaml, install/helm/open-match/Chart.yaml, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backendapi.yaml, install/helm/open-match/templates/frontendapi.yaml, install/helm/open-match/templates/mmlogicapi.yaml, install/helm/open-match/values.yaml, internal/app/backendapi/apisrv/apisrv.go, internal/app/frontendapi/apisrv/apisrv.go, internal/app/mmlogicapi/apisrv/apisrv.go, internal/harness/matchfunction/golang/harness.go, internal/serving/grpcserver.go, internal/serving/testing/fake_frontendapi.go, internal/serving/testing/minimatch.go, internal/serving/testing/minimatch_test.go, internal/statestorage/redis/redishelpers.go, site/config.toml, test/e2e/grpcserver_test.go
=> Release 0.5.1

install/helm/open-match/values.yaml, internal/harness/golang/matchfunction_service.go
It appears the code reads this properly already.  It's just that the missing config probably defaulted to 0, which when assigning a port works.
=> Fix: Frontend config specifies grpcport properly.

Makefile, cloudbuild.yaml
Various fixes to the makefile.
* Ignore delete cluster errors.
* Scope single use global variables.
* Update `make help` command.
* Update versions of tools.
* Reduce the size of the GKE cluster (cheaper and faster startup).
* Fix generation of `install/yaml/` files.
=> Update tools, help, and scope some global vars in Makefile.

cmd/backend/backend.go, cmd/evaluator/evaluator.go, cmd/frontend/frontend.go, cmd/mmlogic/mmlogic.go, internal/testing/fake_frontend.go
For some reason the old format came back for a few files.
=> Update copyright headers

Makefile, go.mod, internal/app/backend/backend_service.go
https://github.com/golangci/golangci-lint/issues/500 is fixed.
=> Enable golangci in presubmit

go.mod, go.sum, internal/statestore/redis_test.go, internal/statestore/testing/fake_redis.go
=> Update miniredis version

api/synchronizer.proto, api/synchronizer.swagger.json, install/helm/open-match/values.yaml, internal/app/synchronizer/evaluator_client.go, internal/app/synchronizer/synchronizer.go, internal/app/synchronizer/synchronizer_service.go, internal/app/synchronizer/synchronizer_service_test.go, internal/pb/synchronizer.pb.go
This PR only implements the core Synchronizer functionality. Wiring this up to backend and actually calling out to the User Evaluator will follow in separate PR. This PR has tests for the core functionality providing a Unit Test evaluation method.
=> Implement core synchronizer functionality.

examples/functions/golang/pool/mmf/matchfunction.go, examples/functions/golang/pool/mmf/matchfunction_test.go
This together with a later PR for a score-based evaluator will show users how to customize open match to generate flexible game matches.
=> Add score to mmf example

Makefile
A privileged user can run `make BASE_VERSION=0.6.0-preview1 _GCB_POST_SUBMIT=1 preview-release --dry-run` to create a release.
=> Add preview deployment script

install/helm/open-match/dashboards/README.md, install/helm/open-match/dashboards/go-processes.json, install/helm/open-match/dashboards/grpc.json, internal/monitoring/public.go, internal/rpc/clients.go, internal/rpc/insecure.go, internal/rpc/tls_server.go
The current dashboard is broken because of the way metrics are emitted.
=> Fix the Grafana Dashboard for Open Match.

Makefile, cloudbuild.yaml, install/terraform/open-match-build/README.md, install/terraform/open-match-build/open-match-build.tf, install/terraform/open-match/README.md, install/terraform/open-match/secure-gke.tf
Make CI validate Terraform templates.
=> Add Terraform Lint and Test

go.mod, go.sum, install/helm/open-match/values.yaml, internal/app/swaggerui/swaggerui.go, internal/monitoring/jaeger.go, internal/monitoring/opencensus_agent.go, internal/monitoring/probe.go, internal/monitoring/prometheus.go, internal/monitoring/public.go, internal/monitoring/stackdriver.go, internal/monitoring/zipkin.go, internal/monitoring/zpages.go, internal/rpc/server.go, internal/rpc/testing/helpers.go, internal/testing/e2e/cluster.go, internal/testing/e2e/common.go, internal/testing/e2e/in_memory.go, internal/util/multiclose.go, internal/util/multiclose_test.go
This change originally was to add OC agent but I noticed a bug with how we flush monitoring and...
This change refactors MultiCloser into the utils package.
=> Fix metrics flushing, add OC agent, and refactor multi-closing.

internal/rpc/clients.go, internal/rpc/insecure.go, internal/rpc/server.go, internal/rpc/tls_server.go
This change introduces instrumentation for HTTP servers and clients.
=> Instrument HTTP clients and servers.

internal/app/backend/backend_service.go, internal/app/synchronizer/evaluator_client.go
This commit replaces the standard json library with the jsonpb library. `jsonpb` has a bunch of non-trivial workarounds for serializations when using the WellKnownTypes defined in `https://developers.google.com/protocol-buffers/docs/reference/google.protobuf`.
=> Replace json with jsonpb

examples/scale/tickets/tickets.go, go.mod, install/helm/open-match/subcharts/open-match-scale/templates/scale-configmap.yaml, install/helm/open-match/subcharts/open-match-scale/values.yaml
=> Add implementation for tickets package to generate fake tickets for scale testing.

Makefile, examples/scale/profiles/multifilter.go, examples/scale/profiles/multipool.go, examples/scale/profiles/util.go, examples/scale/tickets/tickets.go, internal/statestore/redis_indices_test.go
=> Reorder make rule dependencies to fix presubmit

api/messages.proto, internal/statestore/redis_indices.go, internal/statestore/redis_indices_test.go, test/e2e/query_tickets_test.go
Part of moving to the new API proposal: #765
=> Replace boolean filter with tag filter

test/e2e/ticket_test.go
Part of moving to the new API proposal: #765
=> Remove property usage from e2e/ticket_test

examples/functions/golang/pool/mmf/matchfunction_test.go, examples/scale/tickets/tickets.go, internal/app/frontend/frontend_service_test.go, internal/testing/e2e/e2e_test.go, test/e2e/query_tickets_test.go
Part of moving to the new API proposal: #765
=> Remove last references to ticket.properties

.github/ISSUE_TEMPLATE/bugreport.md, .github/ISSUE_TEMPLATE/featurerequest.md, .github/ISSUE_TEMPLATE/release.md
=> Added templates for bug/feature reports

install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/templates/synchronizer.yaml
Part of https://github.com/googleforgames/open-match/issues/680#issuecomment-546538007. The next step is removing the override from the core yaml.
Also resolves #912
=> Remove evaluator config from default config yaml

Makefile, cloudbuild.yaml, csharp/OpenMatch/Annotations.cs, install/helm/open-match/Chart.yaml, install/helm/open-match/values.yaml, third_party/protoc-gen-swagger/options/annotations.proto, third_party/swaggerui/config.json
Bumped all required version to 0.8.0-rc.1 and ran `make release`
=> Release 0.8.0-rc.1

Makefile
I forgot to turn telemetry on after turning the settings off by default in #921
=> Enabled telemetry when generating assets

Makefile, go.mod, install/helm/open-match/values.yaml
All install and static yaml files are tested after turning off the subcharts. Resolved #911 .
=> Turn off subcharts by default

examples/functions/golang/rosterbased/mmf/server.go
Added a few grpc_middleware plugins to help debug the MMF server
=> Added a few grpc_middleware plugins to help debug the MMF server

Makefile, install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/values-production.yaml, install/helm/open-match/values.yaml, internal/statestore/redis.go, internal/statestore/redis_test.go, internal/statestore/testing/fake_redis.go, test/e2e/game_flow_test.go
=> Move ignorelists.ttl from Redis section to Open Match core

Makefile, examples/scale/scenarios/basic_scenario.go, examples/scale/scenarios/util.go, install/helm/open-match/templates/tests/om-test.yaml, test/e2e/match_test.go
This commit added (basically copy & pasting) the roster-based-mmf and default-evaluator implementation for the basic benchmarking scenario.
=> Added mmf and evaluator for the basic benchmarking scenario

examples/scale/scenarios/first_match_scenario.go
Somehow this managed to run from 3:30pm yesterday to 7am this morning without hitting this error.
=> Fix off by 1 error in first match scale test

internal/app/synchronizer/evaluator_client.go, internal/app/synchronizer/synchronizer_service.go
This commit started to stream when calling the evaluator.Evaluate method such that the synchronizer is able to process the data more efficiently.
=> Starts streaming when sending requests from synchronizer to evaluator

Makefile, install/helm/open-match/Chart.yaml
=> Fixed a bug in Chart.yaml redis condition

api/backend.proto, api/query.proto
=> Update proto descriptions to reflect API changes

internal/app/backend/synchronizer_client.go, internal/app/synchronizer/evaluator_client.go, internal/config/cacher.go, internal/config/cacher_test.go
Add new functionality to the cacher allowing it to close old instances.
=>  Fix leaking of client connections by config.Cacher

examples/scale/scenarios/scenarios.go, examples/scale/scenarios/teamshooter/teamshooter.go
See comments for explanation of the scenario.
Snapshot of grafana running this scenario: https://snapshot.raintank.io/dashboard/snapshot/z5gJ8PGr2q8X26KcA7JyhpsPVeMl00MJ
=> implement a scenario which behaves like a team based shooter game

Dockerfile.base-build, Dockerfile.ci, go.mod, third_party/google/api/backend.proto, tutorials/custom_evaluator/director/go.mod, tutorials/custom_evaluator/evaluator/go.mod, tutorials/custom_evaluator/frontend/go.mod, tutorials/custom_evaluator/matchfunction/go.mod, tutorials/custom_evaluator/solution/director/go.mod, tutorials/custom_evaluator/solution/evaluator/go.mod, tutorials/custom_evaluator/solution/frontend/go.mod, tutorials/custom_evaluator/solution/matchfunction/go.mod, tutorials/default_evaluator/director/go.mod, tutorials/default_evaluator/frontend/go.mod, tutorials/default_evaluator/matchfunction/go.mod, tutorials/default_evaluator/solution/director/go.mod, tutorials/default_evaluator/solution/frontend/go.mod, tutorials/default_evaluator/solution/matchfunction/go.mod, tutorials/matchmaker101/director/go.mod, tutorials/matchmaker101/frontend/go.mod, tutorials/matchmaker101/matchfunction/go.mod, tutorials/matchmaker101/solution/director/go.mod, tutorials/matchmaker101/solution/frontend/go.mod, tutorials/matchmaker101/solution/matchfunction/go.mod, tutorials/matchmaker102/director/go.mod, tutorials/matchmaker102/frontend/go.mod, tutorials/matchmaker102/matchfunction/go.mod, tutorials/matchmaker102/solution/director/go.mod, tutorials/matchmaker102/solution/frontend/go.mod, tutorials/matchmaker102/solution/matchfunction/go.mod
The change to third_party/google/api/backend.proto was done by make presubmit.  That's annoying, so I filed https://github.com/googleforgames/open-match/issues/1132
=> Update to go 1.14

Makefile
=> Fix create-gke-cluster version

docs/development.md
This commit updated the development.md file with the latest steps to iterate through Open Match's development journey.
Resolved #1161
=> Update development.md doc

Makefile, install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/templates/tests/om-test.yaml, internal/appmain/apptest/apptest.go, internal/testing/e2e/cluster.go, internal/testing/e2e/in_memory.go
This sets things up for specifying a per-test evaluator and mmf.
=> Have the test instance host the mmf and evaluator

README.md
=> Remove alpha software warning

Makefile, cloudbuild.yaml, cmd/swaggerui/config.json, go.mod, go.sum, install/helm/open-match/Chart.yaml, install/helm/open-match/values-production.yaml, install/helm/open-match/values.yaml, third_party/swaggerui/config.json
=> Release 1.0

Makefile
Update Makefile.
Please look at this update:
https://cloud.google.com/kubernetes-engine/docs/release-notes#may_13_2020
=> Use supported GKE cluster version

internal/app/backend/backend_service.go
=> Fix typo in backend-service.go

Makefile
If there are multiple `gcloud auth list` accounts the command would fail,
adding `grep ACTIVE` to fix and split out this target.
Example:
```
gcloud auth list --format yaml
---
account: numbers-compute@developer.gserviceaccount.com
status: ''
---
account: alexander@example.com
status: ACTIVE
```
=> Make: fix create-gke-cluster target, create clusterRole properly

.github/pull_request_template.md
I suggest using a pull request template. 
Do we have any kind of labels related to PRs? I've checked a bunch of PRs, didn't notice that.
Let's discuss what can be added here as well.
=> Added a PR template

api/matchfunction.proto, api/matchfunction.swagger.json, api/query.proto, api/query.swagger.json, pkg/pb/matchfunction.pb.go, pkg/pb/query.pb.go
Regenerated dependent Swagger and Golang files.
Fix comments in protobuf definition.
Relates to https://github.com/googleforgames/open-match-docs/pull/192
=> Fix spelling in Proto files

internal/app/backend/backend.go, internal/app/backend/backend_service.go, internal/app/frontend/frontend_service_test.go, internal/statestore/instrumented.go, internal/statestore/public.go, internal/statestore/redis.go
- New time to match metric for tickets calculating the time between the ticket creation and it getting and assignment.
=> Added time to assignment metrics to backend

internal/rpc/clients_test.go
Added test for coverage on gRPC functions that are not available.
Adds coverage for #1271 
=> Added test for unavailable gRPC function

Makefile, cloudbuild.yaml, docs/hugo_apiheader.txt, go.mod, go.sum, install/helm/open-match/Chart.yaml, install/helm/open-match/values.yaml, third_party/swaggerui/config.json
This PR uses files that may need to be merged via #1283
=> release-1.1.0-rc.1

internal/api/messages.proto, internal/ipb/messages.pb.go, internal/statestore/backfill.go, internal/statestore/instrumented.go, internal/statestore/public.go
=> Fixed the wrong spelling

.github/CODEOWNERS
This PR adds @sawagh to CODEOWNERS
None
@sawagh is up to speed with the backfill feature and will be helping with code reviews for the same.
=> add @sawagh to codeowners

install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/values-production.yaml, install/helm/open-match/values.yaml, internal/app/frontend/frontend_service_test.go, internal/statestore/redis.go, internal/statestore/testing/fake_redis.go, internal/statestore/ticket_test.go, internal/testing/e2e/backfill_test.go, internal/testing/e2e/cluster_test.go, internal/testing/e2e/common.go
Adds new helm vars for feature configuration
=> Make redis lock expiration configurable

examples/functions/golang/backfill/mmf/matchfunction_test.go, internal/app/query/query_service.go, internal/app/synchronizer/synchronizer_service.go, internal/statestore/backfill_test.go
=> Minor: fixing some typos

internal/app/synchronizer/synchronizer_service.go
There was some names which was not properly updated as part of a
previous PR.
Part of #1080
=>  Fix leftover after PR. Unnamed Channel m7c rename for all variable names.

go.sum, install/helm/open-match/values.yaml, third_party/swaggerui/config.json
Reverts googleforgames/open-match#1367
need to revert due to unwanted changes to open-match/third_party/swaggerui/config.json
=> Revert "Sentinel fix"

.github/CODEOWNERS
Add Andrew Grundy to codeowners/reviewers
=> add andrewgrundy as codeowner

cloudbuild.yaml, tutorials/custom_evaluator/director/go.mod, tutorials/custom_evaluator/evaluator/go.mod, tutorials/custom_evaluator/frontend/go.mod, tutorials/custom_evaluator/matchfunction/go.mod, tutorials/custom_evaluator/solution/director/go.mod, tutorials/custom_evaluator/solution/evaluator/go.mod, tutorials/custom_evaluator/solution/frontend/go.mod, tutorials/custom_evaluator/solution/matchfunction/go.mod, tutorials/default_evaluator/director/go.mod, tutorials/default_evaluator/frontend/go.mod, tutorials/default_evaluator/matchfunction/go.mod, tutorials/default_evaluator/solution/director/go.mod, tutorials/default_evaluator/solution/frontend/go.mod, tutorials/default_evaluator/solution/matchfunction/go.mod, tutorials/matchmaker101/director/go.mod, tutorials/matchmaker101/frontend/go.mod, tutorials/matchmaker101/matchfunction/go.mod, tutorials/matchmaker101/solution/director/go.mod, tutorials/matchmaker101/solution/frontend/go.mod, tutorials/matchmaker101/solution/matchfunction/go.mod, tutorials/matchmaker102/director/go.mod, tutorials/matchmaker102/frontend/go.mod, tutorials/matchmaker102/matchfunction/go.mod, tutorials/matchmaker102/solution/director/go.mod, tutorials/matchmaker102/solution/frontend/go.mod, tutorials/matchmaker102/solution/matchfunction/go.mod
Resolves go.mod issues with deploying open match tutorials
**Which issue(s) this PR fixes**: 
#1171 
Closes #
None
Part 1 of 2 of closing issue #1171. Will close that issue once the go.mod files have been fixed in 1.2.1 PR.
=> Release 1.1.1

cloudbuild.yaml, tutorials/custom_evaluator/director/go.mod, tutorials/custom_evaluator/evaluator/go.mod, tutorials/custom_evaluator/frontend/go.mod, tutorials/custom_evaluator/matchfunction/go.mod, tutorials/custom_evaluator/solution/director/go.mod, tutorials/custom_evaluator/solution/evaluator/go.mod, tutorials/custom_evaluator/solution/frontend/go.mod, tutorials/custom_evaluator/solution/matchfunction/go.mod, tutorials/default_evaluator/director/go.mod, tutorials/default_evaluator/frontend/go.mod, tutorials/default_evaluator/matchfunction/go.mod, tutorials/default_evaluator/solution/director/go.mod, tutorials/default_evaluator/solution/frontend/go.mod, tutorials/default_evaluator/solution/matchfunction/go.mod, tutorials/matchmaker101/director/go.mod, tutorials/matchmaker101/frontend/go.mod, tutorials/matchmaker101/matchfunction/go.mod, tutorials/matchmaker101/solution/director/go.mod, tutorials/matchmaker101/solution/frontend/go.mod, tutorials/matchmaker101/solution/matchfunction/go.mod, tutorials/matchmaker102/director/go.mod, tutorials/matchmaker102/frontend/go.mod, tutorials/matchmaker102/matchfunction/go.mod, tutorials/matchmaker102/solution/director/go.mod, tutorials/matchmaker102/solution/frontend/go.mod, tutorials/matchmaker102/solution/matchfunction/go.mod
Fixes go.mods for tutorials
Closes #
#1171
=> release v1.2.1

Makefile
Workload Identity was disabled in PR #947 because of a bug. It has since been fixed. There is no lost impact or performance to Open Match so re-enabling this feature.
Closes #
#951 
=> re-enable workload identity

Makefile, cloudbuild.yaml, install/helm/open-match/Chart.yaml, install/helm/open-match/values.yaml
Release 1.3.0-rc.1
Closes #1387
=> Release 1.3.0-rc.1

Makefile, cloudbuild.yaml, install/helm/open-match/Chart.yaml, install/helm/open-match/values.yaml, install/terraform/open-match-build/README.md, install/terraform/open-match/README.md, internal/config/config_test.go, internal/testing/e2e/cluster.go, internal/testing/e2e/cluster_test.go, internal/testing/e2e/in_memory.go, third_party/swaggerui/config.json
Updates for the release candidate for v 1.4.0
Closes #
This is linked to the release issue #1446
=> Release 1.4.0-rc.1 

tutorials/custom_evaluator/director/Dockerfile, tutorials/custom_evaluator/evaluator/Dockerfile, tutorials/custom_evaluator/frontend/Dockerfile, tutorials/custom_evaluator/matchfunction/Dockerfile, tutorials/custom_evaluator/solution/director/Dockerfile, tutorials/custom_evaluator/solution/evaluator/Dockerfile, tutorials/custom_evaluator/solution/frontend/Dockerfile, tutorials/custom_evaluator/solution/matchfunction/Dockerfile, tutorials/default_evaluator/director/Dockerfile, tutorials/default_evaluator/frontend/Dockerfile, tutorials/default_evaluator/matchfunction/Dockerfile, tutorials/default_evaluator/solution/director/Dockerfile, tutorials/default_evaluator/solution/frontend/Dockerfile, tutorials/default_evaluator/solution/matchfunction/Dockerfile, tutorials/matchmaker101/director/Dockerfile, tutorials/matchmaker101/frontend/Dockerfile, tutorials/matchmaker101/matchfunction/Dockerfile, tutorials/matchmaker101/solution/director/Dockerfile, tutorials/matchmaker101/solution/frontend/Dockerfile, tutorials/matchmaker101/solution/matchfunction/Dockerfile, tutorials/matchmaker102/director/Dockerfile, tutorials/matchmaker102/frontend/Dockerfile, tutorials/matchmaker102/matchfunction/Dockerfile, tutorials/matchmaker102/solution/director/Dockerfile, tutorials/matchmaker102/solution/frontend/Dockerfile, tutorials/matchmaker102/solution/matchfunction/Dockerfile
This PR updates the dockerfiles for all tutorials with the version 1.4.0-rc.1 which would help in building the docker images for trying out these tutorials.
Closes #
=> update tutorials dependency for version 1.4.0-rc.1

api/frontend.swagger.json
https://github.com/googleforgames/open-match/issues/1405
=> fixing 404 response parser

install/helm/README.md
Just fixing a little typo problem in the `install/helm/README.md` file
Space typo
=> Adjust Helm README spaces for portType ClusterIP

internal/app/query/cache.go, internal/app/query/query.go
This PR adds metrics proposed in #1482.
Closes #1482 
This PR is a work in progress and issue can be reopened to add additional metrics
=> Added metrics for ticket behavior

tutorials/custom_evaluator/director/Dockerfile, tutorials/custom_evaluator/evaluator/Dockerfile, tutorials/custom_evaluator/frontend/Dockerfile, tutorials/custom_evaluator/matchfunction/Dockerfile, tutorials/custom_evaluator/solution/director/Dockerfile, tutorials/custom_evaluator/solution/evaluator/Dockerfile, tutorials/custom_evaluator/solution/frontend/Dockerfile, tutorials/custom_evaluator/solution/matchfunction/Dockerfile, tutorials/default_evaluator/director/Dockerfile, tutorials/default_evaluator/frontend/Dockerfile, tutorials/default_evaluator/matchfunction/Dockerfile, tutorials/default_evaluator/solution/director/Dockerfile, tutorials/default_evaluator/solution/frontend/Dockerfile, tutorials/default_evaluator/solution/matchfunction/Dockerfile, tutorials/matchmaker101/director/Dockerfile, tutorials/matchmaker101/frontend/Dockerfile, tutorials/matchmaker101/matchfunction/Dockerfile, tutorials/matchmaker101/solution/director/Dockerfile, tutorials/matchmaker101/solution/frontend/Dockerfile, tutorials/matchmaker101/solution/matchfunction/Dockerfile, tutorials/matchmaker102/director/Dockerfile, tutorials/matchmaker102/frontend/Dockerfile, tutorials/matchmaker102/matchfunction/Dockerfile, tutorials/matchmaker102/solution/director/Dockerfile, tutorials/matchmaker102/solution/frontend/Dockerfile, tutorials/matchmaker102/solution/matchfunction/Dockerfile
**What this PR does / Why we need it**: This PR updates the version dependency of tutorials to v1.5.0-rc.1
Closes #
=> Additional changes to release-1.5

internal/app/query/query.go
There is currently an incorrect measure set in the "open-match.dev/query/backfills_per_query" view. This is the fix.
Closes #
=> fix metrics for backfills per query

.github/CODEOWNERS
Removal of myself from CODEOWNERS since I no longer actively participate in the community.
N/A
Thank you for letting be a part of this awesome project!
=> Removal of myself from CODEOWNERS
