googleforgames/open-match

README.md
Changed one word, but don't see why github has also highlighted line 214. There were no spacing or line break changes there; not sure what it's on about ¯\\\_(ツ)_/¯
=> README.md: small spelling fix

cmd/backendapi/main.go, cmd/frontendapi/main.go, cmd/mmforc/main.go, config/config.go, config/matchmaker_config.json, internal/statestorage/redis/redishelpers.go
Changes proposed
- Add support for redis authentication. Currently it assumes the keys for `redis.user` and `redis.password` are set in `matchmaker_config.json`. If this needs to be moved to look at env vars or similar, can do.
- Refactored redis connection pool to live in `redishelpers` (avoids duplication) and updated `backendapi`, `frontendapi`, and `mmforc` entry points to use this helper method.
- Misc clean up, such as; removed unreferenced packages and removed trailing whitespace.
=> Add redis auth and move connection to redishelpers

README.md, docs/development.md, docs/faq.md
Misc documentation fixes.
I also updated the section about redis connection details and removed the note about redis auth since that was implemented in https://github.com/GoogleCloudPlatform/open-match/pull/26.
=> Documentation fixes

docs/development.md
In the ``docs/development.md`` is a typo related to the command used for building the base image
=> Fix typo in development guide

README.md, config/config.go, deployments/k8s/redis_service.json, docs/development.md, examples/evaluators/golang/simple/main.go, examples/functions/csharp/simple/Program.cs, examples/functions/golang/manual-simple/main.go, install/yaml/01-redis-failover.yaml, install/yaml/01-redis.yaml, install/yaml/README.md, test/cmd/client/main.go
This PR provides an alternative to default "single instance Redis" option:
- Replica set of 3 Redis instances and 3 Sentinels for a failover ([Redis Operator](https://github.com/spotahome/redis-operator) must be installed in cluster)
- Since Redigo doesn't support Sentinel, there's a HAProxy based workaround. Inside the pod, there's a shell script that is monitoring master address (asking Sentinels every second). And if address changes then the script refreshes HAProxy configuration without the restart (writing changes to 'stats socket')
=> Optional Redis HA deployment for #41

cmd/backendapi/apisrv/apisrv.go, cmd/frontendapi/apisrv/apisrv.go, config/matchmaker_config.yaml, internal/expbo/unmarshal.go, internal/expbo/unmarshal_test.go, internal/statestorage/redis/redispb/matchobject.go, internal/statestorage/redis/redispb/player.go
Possible solution for #59.
Yes, it's weird to configure backoff this way, but it gives some flexibility, so we may get rid of it once we figure out best suitable values for BO params.
=> added configurable backoff to MatchObject and Player watchers

.gitignore
Goland is a free golang ide from jetbrains. This prevents metadata files from accidentally getting checked into source.
=> Update git ignore to ignore goland ide files

install/helm/open-match/dashboards/README.md, install/helm/open-match/dashboards/rpc.json
It wasn't included in https://github.com/GoogleCloudPlatform/open-match/pull/81 because the *.json in .gitignore.
=> Add RPC dashboard.

Makefile
I created a Makefile that might hopefully make some parts of development easier as I switch between Linux and Mac OS X pretty often.
You can choose to use this a la carte.
It supports:
* Protobuf generation and placement of those files.
* Building all golang artifacts
* Building all the images.
* Sane default Minikube and GKE clusters.
* Push helm chart deployment of Open Match, Prometheus, and Grafana
Dependencies Required:
* go
* Python3
* make
Other dependencies like protoc, protoc-gen-go, etc are downloaded into the build/toolchain/ directory automatically.
=> Makefile for simpler development

install/yaml/02-open-match.yaml
This touches on https://github.com/GoogleCloudPlatform/open-match/issues/46 where we should move towards Prometheus service discovery.
=> Add Prometheus service discovery annotations to the Open Match servers.

.dockerignore, Dockerfile.base-build, Makefile, README.md
This change addresses https://github.com/GoogleCloudPlatform/open-match/issues/143.
* Fix build dependencies
* Add README stickers
* Switch back to '.' from source since some shells don't like it.
Because we don't have CI coverage for make yet here's the command I ran in a GCE VM to verify the build.
```bash
sudo rm -rf workspace/ \
&& export GOPATH=$HOME/workspace \
&& export GO111MODULE=on \
&& mkdir -p workspace/src/github.com/GoogleCloudPlatform \
&& cd workspace/src/github.com/GoogleCloudPlatform/ \
&& git clone https://github.com/jeremyje/open-match.git \
&& cd open-match \
&& git checkout -b fixdeps origin/fixdeps \
&& make install-toolchain \
&& make install-npm build/site/ \
&& make all build-images -j8
```
=> Fix dependency issues in the build.

cmd/backendapi/matchmaker_config.yaml, cmd/frontendapi/matchmaker_config.yaml, cmd/mmforc/matchmaker_config.yaml, cmd/mmlogicapi/matchmaker_config.yaml, examples/evaluators/golang/simple/matchmaker_config.yaml, examples/functions/golang/manual-simple/matchmaker_config.yaml
There's still a symlink remaining on the helm chart. Not sure how to get rid of that one but suggestions welcome.
=> Remove symlinks to config files because they are mounted via ConfigMaps.

cloudbuild.yaml
PHP image build is very expensive because it has to download all the debian build tools like clang to build protobuf and grpc C++ libraries. This alongside all the other build artifacts takes a very long time.
=> Disable the PHP example during the CI build.

Makefile
It is missing a dash on one of the arguments, which breaks things.
=> Fix 'make create-gke-cluster'

site/app.yaml
When starting the dev_appserver.py to run the Open Match website locally you encounter an error that says: There are too many files in your application for changes in all of them to be monitored.  This change fixes that.
=> Ignore unused directories

Makefile
This fix issue #180. go build is able to download a temporary source package and build the binaries into -pkgdir directory, which isolates the build environment from users' environment.
Also fixed the REPOSITORY_ROOT variable. This variable used to contains a trailing forward slash e.g. 'src/', which makes BUILD_DIR turns to an invalid path 'src//build'.
=> Fix build artifacts

README.md
https://github.com/GoogleCloudPlatform/open-match/issues/206
=> Bump required Go version because of a dependency.

Makefile, cloudbuild.yaml
Resolves https://github.com/GoogleCloudPlatform/open-match/issues/212
The root cause is that we disable downloading of go modules during the go build process in an effort to avoid races if 2 binaries are built at the same time. This causes other issues like this one so we'll enable it for now.
=> Move GOPROXY=off to CI only.

internal/harness/matchfunction/golang/apisrv/apisrv.go, internal/harness/matchfunction/golang/apisrv/function_stats.go, internal/harness/matchfunction/golang/harness.go
Added core logic to the GRPC Harness to do the following:
- Query the Player Pools in Open Match
- Call MatchFuntion written by the developer
- Create Proposals for the results sent by the Match Functions
=> Core Logic for the GRPC Harness (#125)

.dockerignore, .gitignore, Makefile, cloudbuild.yaml, config/matchmaker_config.yaml, examples/evaluators/golang/serving/Dockerfile, examples/evaluators/golang/serving/main.go, internal/harness/evaluator/golang/apisrv/apisrv.go, internal/harness/evaluator/golang/apisrv/evaluator_stats.go, internal/harness/evaluator/golang/doc.go, internal/harness/evaluator/golang/harness.go
This PR implements a generic Evaluator harness that abstracts all the Open Match specific data concepts (Redis reads etc.) away from the user's evaluation function. In future releases, these will change completely and the user logic should still be minimally impacted. 
The PR also implements a sample barebones evaluator example that simply de-collides proposals.
=> Evaluator Harness and Sample golang Evaluator

.gitignore, Makefile, go.mod, tools/certgen/certgen.go, tools/certgen/internal/internal.go, tools/certgen/internal/internal_test.go, tools/certgen/testing/certbundle.go, tools/certgen/testing/certbundle_test.go
This change adds a self-signed certificate generation tool to assist with creating certificates used with gRPC TLS mode.
It's possible to use openssl as well but this is simpler since there's no CSR workflow required here.
=> Self-Certificate generation for Open Match. (#273)

README.md
* Fixing a few typos
* On Windows shell, you can't use backticks to catch the result of a program call as a string, I believe the standard way to do that is to use the **for** command to catch the result in a variable and then use it. I included that version in the "Deploying Open Match" section, as the current version does not work on Windows.
=> Update README.md to add Windows batch line version

docs/gcloud.md
While following documentation to create a cluster for Open Match using GCP, the command line example says to create using n1-standard-4 machine type. 
It seems like it is not possible when on a free tier, at least on the default settings (new account)
`C:\Program Files (x86)\Google\Cloud SDK>gcloud container clusters create --machine-type n1-standard-4 open-match-dev-cluster --zone us-west1-a --tags open-match`
`ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Insufficient regional quota to satisfy request: resource "CPUS": request requires '12.0' and is short '4.0'. project has a quota of '8.0' with '8.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project=XXXXX`
To remove as many potential hurdles for people …
=> Update gcloud.md steps to work with free tier

internal/serving/grpcserver.go, internal/util/netlistener/listener_holder.go, internal/util/netlistener/listener_holder_test.go, test/e2e/grpcserver_test.go
On machines that have IP v6 enabled localhost appears as `[::]:PORT` on IPv4 it's `:PORT`. When using certgen there's issues assuming IPv4 style when using server overrides to validating certificates.
Resolves #298
Resolves #297
=> Add ListenerHolder.AddrString() to avoid bad IPv6 assumptions. (#298) (#297)

Makefile
Break out the dependencies for remote includes a bit better and add the option protos from protoc-gen-swagger so that we can annotate the APIs in the Swagger doc.
=> Add protoc-gen-swagger proto options to includes.

Makefile
As we move away from the old binaries we should have their build targets easy to differentiate from the new targets.
All the deprecated targets are now prefixed with `deprecated-` (where possible) and are moved to the bottom of the `Makefile`.
=> Move all deprecated Makefile targets to the bottom.

install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/values.yaml
This change adjusts the helm chart to point to the new binaries when creating an Open Match cluster.
The example has not been changed yet since there's no example clients yet.
=> Replace helm chart for the new binaries.

internal/future/storage/public.go, internal/future/storage/redis.go, internal/future/storage/redis_test.go
This is a very basic and unused Redis abstracted layer for data access.
It provides basic API to put and get data. It also has a method to get the redis connection pool directly for old code.
=> Add stubbed abstracted Redis client.

Makefile, README.md, doc.go, internal/future/statestore/public.go, internal/serving/bindata/backend/bindata.go, internal/serving/bindata/frontend/bindata.go, internal/serving/bindata/matchfunction/bindata.go, internal/serving/bindata/mmlogic/bindata.go, internal/serving/testing/minimatch_test.go, site/handler.go, site/redirect/redirection.go
* Enforce `import open-match.dev/open-match`. `import github.com/GoogleCloudPlatform/open-match` is now blocked.
* Fixed bug in post submit where default website crashes the build and can hang if there's a TTY.
* Add gofmt to `make fmt` and `make presubmit` to auto fix some golangci issues.
* Fix outdated URLs in the `README.md` badges.
Verified the build site via `make _GCB_POST_SUBMIT=1 _GCB_LATEST_VERSION=0.0 ci-deploy-site`
=> Fix URLs, Post Submit, add gofmt to presubmit

internal/app/backend/backend.go, internal/app/backend/backend_test.go, internal/app/frontend/frontend.go, internal/app/frontend/frontend_test.go, internal/app/minimatch/minimatch.go, internal/app/mmlogic/mmlogic.go, internal/app/mmlogic/mmlogic_test.go, internal/harness/golang/harness.go, internal/rpc/insecure.go, internal/rpc/insecure_test.go, internal/rpc/server.go, internal/rpc/server_test.go, internal/rpc/testing/server.go, internal/rpc/testing/server_test.go, internal/rpc/tls_server.go, internal/rpc/tls_server_test.go
There will be a client wrapper coming in using the same Params pattern. This commit rename server related structs and functions with a 'Server' prefix to better distinguish them from the client ones.
=> Rename serving functions and params with 'Server' prefix

Makefile, cloudbuild.yaml, docs/knative.md
This change scans our Markdown documents (excluding site/ and some others) for 404 links.
=> Add validation for markdown links

internal/app/backend/backend_service.go
Add input validation to FetchMatches. The call now fails with InvalidArgument if match configuration is missing or unsupported.
=> Fail FetchMatches if match configuration is missing or unsupported

internal/app/mmlogic/mmlogic_service.go, internal/harness/golang/matchfunction_service.go, internal/statestore/redis.go, internal/util/netlistener/listener_holder.go
Here are the issues this change fixes:
1. Add error check to avoid accessing failed connection in tcp net listener
2. Divide by zero error in the redis state storage library if page size is 0.
3. Ability to support null hostname when connecting to mmlogic client in match function harness.
4. Set min / max page size limits to initialize correctly if page size is set to unsupported values.
=> Fix minor issues that were encountered in an E2E test case for generating matches.

Makefile
The default open-match configuration for GKE tries to be as tight as possible to reduce billing while trying it out. Sometimes Kubernetes does not binpack the pods as well and may run out of room. This change enables some autoscaling for those scenarios.
=> Enable GKE Autoscaling

Makefile, install/policies/binauthz.yaml, site/content/en/docs/Installation/setup-gke.md
Binary authorization adds mitigations to a GCP project from running unauthorized code. This change adds some groundwork to add an example of using binauthz for Open Match.
=> Add Binary Authorization commands.

install/helm/open-match/values.yaml, internal/config/view.go, internal/statestore/redis.go, internal/statestore/redis_test.go
open match v.5's backoff config is a bit unnatural. This commit aims to make config easier to understand and configurable.
=> Make backoff strategy configurable

Makefile
The "v" was missing from the kind urls, so it wasn't properly downloaded.
Additionally, KinD does not update the kube config, so the makefile can't automatically configure future kubecfg commands to work properly.  As an easy fix, just tell the user to run the commands themselves.
See https://github.com/googleforgames/open-match/pull/500 for KinD context.
This fixes #497
=> Fix KinD make commands

install/helm/open-match/values.yaml
Resolves #217. `.Values.grafana.enabled` is not set so what being passed to helm from `templates/grafana-dashboards.yaml` is empty, which turns into a deletion error since this template does not have a valid object to be deleted.
=> Fix helm deletion error

.golangci.yaml, Makefile, internal/rpc/clients_test.go, internal/rpc/server_test.go
Golangci 1.17.1 resolves its original segfault issue. It includes gofmt and govet so I use to replace these two presubmit checks.
This commit disable the `bodyclose` plugin when running golangci against the test files as it only accepts closing the http body with specific pattern.
=> Update golangci version and enable it in presubmit check

internal/app/backend/backend_service.go
Per discussion, `backend.FetchMatches` returns safely unless the context is canceled. FetchMatches moves to the next response candidate if it encounters any internal issues
=> Update the behavior of backend.FetchMatches

internal/filter/filter.go, internal/filter/filter_test.go, internal/filter/testcases/testcases.go
This package will be useful for a simple definition of how filters work, as well as a way to process tickets without relying on indexes.  This will allow other filter types (eg, strings) to be added without a redis implementation.  See package documentation for some more details.
I plan on replacing the current redis indexing with a "all tickets" index to remove the edge cases it gets wrong that we don't want to spend time fixing for v0.6.  Instead this package will be responsible for filtering which tickets to return.  This also removes the index configuration problem from v0.6. Then for v0.7, once the indexing and database solutions are chosen, we can go back to implementing the correct way to be indexing tickets.
Also included are test cases, separated in their own definition.  These …
=> Add filter package

go.mod, go.sum, internal/statestore/redis.go, internal/statestore/redis_test.go
The original implementation is not sensitive to the context, and will return a connection even if a cancelled context is passed into the `redisBackend.connect` function. This requires updating the `redigo` module to the bleeding edge and this `DialContext` instead of calling `Dial`.
This commit also adds a the resource closer to the statestore tests in `statestore/redis_test.go`
=> Fix a bug in redis connect

Dockerfile.ci, Makefile
* `sed -i` commands work on macOS.
* Use absolute paths for `Makefile` targets.
* Merge website build targets in prep for move to open-match-docs.
=> Use absolute paths in the makefile. Fix macos sed bug.

.dockerignore, .gitignore, Makefile, cloudbuild.yaml, go.mod, tools/certgen/internal/internal_test.go, tools/reaper/internal/internal.go, tools/reaper/internal/internal_test.go, tools/reaper/reaper.go
This is a command line tool to purge leaked clusters that will occur when there's CI test failures during cluster based end to end tests.
This command line tool may not exist as is when we need to actually start doing e2e testing. It might change to a Cloud Scheduler job.
=> Create cluster reaper for Open Match e2e tests. (#88)

cloudbuild.yaml
CI is broken because we reference redis somewhere in the docs and redis's certificate https://redis.io/ just expired. Temporarily disable md-test until redis.io comes back.
=> Temorarily disable md-test CI check

README.md
Open match logo points to a broken `/site/static` link. This commit change the link to [https://github.com/googleforgames/open-match-docs/blob/master/site/static/images/logo-with-name.png](https://github.com/googleforgames/open-match-docs/blob/master/site/static/images/logo-with-name.png)
=> Fix open match logo

Makefile, cloudbuild.yaml, examples/functions/golang/pool/matchfunction_test.go, examples/functions/golang/soloduel/matchfunction_test.go, internal/app/backend/backend_service_test.go, internal/filter/filter_test.go, internal/statestore/redis_test.go, tools/reaper/Dockerfile, tools/reaper/internal/internal.go, tools/reaper/internal/internal_test.go, tools/reaper/reaper.go
* Added a serving mode for Cluster Reaper
* Add a docker image for the cluster reaper.
* Updated Makefile to use `$(GCLOUD)` instead of `gcloud` for control over verbosity.
* Post submit builds will generate images with the `:canary` label instead of `:dev`.
* Re-enable markdown tests.
For the cluster reaper the plan will be to create a Cloud Run deployment that serves it and a Cloud Scheduler job that tickles it every minute to delete orphaned clusters.
=> Prepare CI for Cluster E2E Testing

Makefile, cloudbuild.yaml
This change adds `:canary`, `:$DATE-canary`, and `:$VERSION-canary` tags to the open-match-build docker images.
This also creates a macro'ed version of `push-%-image:` make target.
A short coming of the implemented approach is that the images are published while the rest of the build is running so if there's flaky tests or so the images might get published. I think this is worth the trade off for reducing code duplication given that presubmits are already required.
=> Add canary image tags. (#539)

cmd/swaggerui/Dockerfile
Add slash in URL to prevent double appendage in Chrome.
=> Fix Swagger UI errors.

Makefile
It turns out that 1.13.6.gke.6 which is a very new version is no longer supported. Scaling back the version number to just 1.13.6 since that should still exist.
```
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Master version "1.13.6-gke.6" is unsupported.
```
=> Fix CI: Switch to a Supported GKE Version

install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/demo.yaml, install/helm/open-match/templates/demofunction.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/templates/swaggerui.yaml, install/helm/open-match/templates/synchronizer.yaml, install/helm/open-match/values.yaml
This change makes it possible to talk to Open Match outside of the Kubernetes cluster.
This unblocks the e2e testing story for on cluster tests.
=> Expose services as backed by a LoadBalancer.

internal/app/backend/backend.go, internal/app/backend/backend_service.go, internal/app/backend/synchronizer_client.go, internal/app/minimatch/minimatch.go, test/e2e/minimatch/minimatch_setup.go
This enables minimatch test setup to set up the synchronizer host, port on the configuration after all the services are up.
=> Implement synchronizer client that only establishes connection to the synchronizer on the first call.

.gitignore, Dockerfile.ci, Makefile, install/terraform/open-match-build/README.md, install/terraform/open-match-build/open-match-build.tf, install/terraform/open-match-build/terraform.tfstate
This change introduces Terraform management of Open Match CI. Right now it'll manage the subnets and service accounts used to allow CI to run. This is GCB/prow agnostic.
Lastly, this change mitigates the subnet collision bug in GKE by provisioning a cluster on it's own subnetwork based on the second the build runs. This isn't a perfect solution but it should mitigate the vast majority of collisions we are seeing.
=> Codify Open Match Continuous Integration as a Terraform template and migrate CI collisions. (#576)

.dockerignore, Dockerfile.base-build, Makefile, cloudbuild.yaml
Reorganize some build steps to only download the cached image once.
Change the `make push-helm` to wait for the tiller pod instead of the tiller deployment.
=> Reduce Time in CI

Dockerfile.ci, Makefile, cloudbuild.yaml, internal/testing/e2e/README.md, internal/testing/e2e/cluster.go, internal/testing/e2e/common.go, internal/testing/e2e/common_test.go, internal/testing/e2e/e2e_test.go, internal/testing/e2e/in_memory.go, test/e2e/tickets/query_tickets_test.go, test/e2e/tickets/ticket_test.go
This change enables e2e cluster test to run in CI. Previously it was possible to run e2e against a cluster via `make e2ecluster` but not in CI. This change adds support to scan for a Kubernetes config file via the `KUBECONFIG` environment variable in the test framework and also assign a hard coded path to `KUBECONFIG` in the open-match-build CI docker image.
=> Enable E2E Cluster Tests

Makefile, cloudbuild.yaml, examples/evaluator/golang/simple/evaluate/evaluator.go, examples/evaluator/golang/simple/main.go, examples/functions/golang/pool/Dockerfile, examples/functions/golang/pool/main.go, examples/functions/golang/pool/mmf/matchfunction.go, examples/functions/golang/pool/mmf/matchfunction_test.go, examples/functions/golang/soloduel/mmf/matchfunction.go, examples/functions/golang/soloduel/mmf/matchfunction_test.go, install/helm/open-match/values.yaml, test/e2e/minimatch/evaluator_setup.go, test/e2e/minimatch/mmf_setup.go
This commit adds the e2eevaluator and e2ematchfunction to the `make install-chart` command. Will add the helm charts and modify the cloudbuild file in a later PR.
=> Add e2eevaluator and e2ematchfunction setup

Makefile, cmd/swaggerui/Dockerfile, cmd/swaggerui/config.json, install/helm/open-match/values.yaml, internal/app/swaggerui/swaggerui.go, internal/config/config.go, third_party/swaggerui/config.json, third_party/swaggerui/index.html
Swaggerui will now show a list of all the APIs that are available based on the `matchmaker_config.yaml` and route to the appropriate service. This change will also be ported to the website.
=> Config based Swagger UI

go.sum, internal/app/backend/backend.go, internal/app/backend/backend_service.go, internal/app/backend/backend_service_test.go, internal/rpc/clientcache.go, internal/rpc/clientcache_test.go, internal/rpc/clients.go, internal/rpc/clients_test.go
The RPC client cache will be used for the MMF frontend service in addition to the backend service. This change breaks it out from the backend and adds tests for it.
=> Break out rpc client cache for reuse.

Makefile
This change simply removes duplication in the Makefile for declaring build docker rules for the service binaries. The push-*-image rules already have this treatment. The special thing with the build rules is the `Dockerfile` is not in a specific location so we can only support the service binaries for this pattern.
=> Make default build-*-image rule point to cmd/*/Dockerfile

Makefile, examples/demo/main.go, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/demo.yaml, install/helm/open-match/templates/demoevaluator.yaml, install/helm/open-match/templates/demofunction.yaml, install/helm/open-match/templates/e2eevaluator.yaml, install/helm/open-match/templates/e2ematchfunction.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/templates/podsecuritypolicy.yaml, install/helm/open-match/templates/swaggerui.yaml, install/helm/open-match/templates/synchronizer.yaml, install/helm/open-match/values.yaml, internal/app/swaggerui/swaggerui.go, internal/monitoring/probe.go, internal/monitoring/probe_test.go, internal/rpc/clients_test.go, internal/rpc/insecure.go, internal/rpc/server_test.go, internal/rpc/tls_server.go
Remove redundant pullPolicy for images and unify the health checking logic for all services.
The health checker is now stateful so it can report more useful log messages.
=> Config cleanup and improved health checking (#623)

install/helm/open-match/Chart.yaml
This is an artifact that was moved to open-match-docs.
=> Fix Open Match logo in Helm chart

go.mod, go.sum, install/helm/open-match/dashboards/README.md, install/helm/open-match/values.yaml, internal/monitoring/public.go, internal/rpc/clients.go, internal/rpc/insecure.go, internal/rpc/server.go, internal/rpc/testing/helpers.go, internal/rpc/tls_server.go, internal/testing/e2e/cluster.go
This change introduces verbose logging mode for gRPC calls and the enablement of metrics based on Prometheus being configured.
The `matchmaker_config.yaml` will have a new option to enable RPC verbose logging:
```yaml
logging:
rpc: true
```
This change also introduces a few other gRPC middlewares (panic-recovery, and API field validation). API field validation is not currently used yet but the protos will be updated soon.
=> Add config based metrics and logging for gRPC.

install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/demo.yaml, install/helm/open-match/templates/demoevaluator.yaml, install/helm/open-match/templates/demofunction.yaml, install/helm/open-match/templates/e2eevaluator.yaml, install/helm/open-match/templates/e2ematchfunction.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/templates/service-account.yaml, install/helm/open-match/templates/swaggerui.yaml, install/helm/open-match/templates/synchronizer.yaml, install/helm/open-match/values.yaml
This change reduces the duplication of configuration between each template. The YAML produced is functionally the same but the ordering of some elements is different.
=> Refactor Helm deployment templates to share common config.

.golangci.yaml, Makefile, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/demoevaluator.yaml, install/helm/open-match/templates/demofunction.yaml, install/helm/open-match/templates/e2eevaluator.yaml, install/helm/open-match/templates/e2ematchfunction.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/templates/synchronizer.yaml, install/helm/open-match/templates/tls-secret.yaml, install/helm/open-match/values.yaml, internal/app/backend/backend_service_test.go, internal/app/swaggerui/swaggerui.go, internal/rpc/clients.go, internal/rpc/clients_test.go, internal/rpc/server.go, tools/certgen/certgen.go
This change allows someone to deploy Open Match with TLS encryption.
This mode will not be enabled by default (for now) because of the added configuration complexity. The demo and swaggerui will still serve on HTTP (because there's no compelling reason to do HTTPS for them and they don't use the `internal/rpc/` package for serving). They are however communicating to their backends using HTTPS.
=> Add TLS support to the Helm chart.

.golangci.yaml, install/helm/open-match/dashboards/storage.json, install/helm/open-match/dashboards/tickets.json, install/helm/open-match/values.yaml, internal/app/backend/backend.go, internal/app/backend/backend_service.go, internal/app/backend/synchronizer_client.go, internal/app/frontend/frontend.go, internal/app/frontend/frontend_service.go, internal/app/minimatch/minimatch.go, internal/app/mmlogic/mmlogic.go, internal/app/mmlogic/mmlogic_service.go, internal/app/swaggerui/swaggerui.go, internal/app/synchronizer/synchronizer.go, internal/app/synchronizer/synchronizer_service.go, internal/monitoring/prometheus.go, internal/monitoring/public.go, internal/monitoring/public_test.go, internal/rpc/clients.go, internal/rpc/server.go, internal/statestore/instrumented.go, internal/statestore/public.go, internal/statestore/redis.go, internal/statestore/redis_test.go
This is a first pass and very rough attempt at adding specific metrics to Open Match. Many of these metrics may not be immediately useful but we need something in for now so that we can build dashboards and analyze key metrics based on stress testing.
This change is also removing some logger instances. There will be a future changes to make 1 logger per package unless there's a reason to keep a separate one for example, delegated client calls.
=> Add metrics for Open Match

internal/config/config.go, internal/rpc/insecure.go, internal/rpc/tls_server.go, pkg/harness/evaluator/golang/evaluator_service.go, pkg/harness/evaluator/golang/harness.go, pkg/harness/function/golang/harness.go, pkg/harness/function/golang/matchfunction_service.go
We are moving to a model where there's 1 logger per package. Some extra loggers are ok if they make sense. Like the rpc package has a client and server logger.
This change does not include the logger merge for monitoring package. That's in https://github.com/googleforgames/open-match/pull/648
=> Merge logrus loggers

internal/rpc/clients.go, internal/rpc/testing/helpers.go, internal/testing/e2e/cluster.go
Replace `Hostname` and `Port` from `ClientParams` with `Address` field to simplify and reduce the amount of transforms between each.
=> Simplify HTTP client construction.

internal/util/netlistener/listener_holder.go, tools/reaper/internal/internal_test.go
In unit tests, Open Match serves on random TCP ports that accept traffic anywhere. This causes a lot of firewall alerts to popup when running the unit tests. This change causes Open Match to serve on `localhost:$PORT` when running in unit test mode. (Really when a random port is used.)
=> Open local TCP ports in tests to prevent firewall dialogs.

Dockerfile.base-build
First copy only the go.sum and go.mod then download dependencies. Docker
caching is [in]validated by the input files changes.  So when the dependencies
for the project don't change, the previous image layer can be re-used.  go.sum
is included as its hashing verifies the expected files are downloaded.
I'm ignoring cases where the go.mod is missing a dep for now.  Later go commands will
fetch the missing deps, and they should make their way into go.mod sooner rather than later.
If it's a mess, it can be cleaned up later.
The time comparison of building all images from before and after is:
clean build: 7m22s -> 7m22s
after small change to demo: 5m59 -> 5m7s
So no speed increase for purely fresh builds (as expected), but saves a minute when deps haven't changed from the last build.
=> Cache dependency downloads by first adding only go module to Dockerfile

cloudbuild.yaml
The binaries generated in cloudbuild can only be used under kubernetes environment as they requires reading `match_maker.yaml` config from `/app/config` directory - which get created by volume mount. Therefore, uploading these artifacts to our gcs bucket only makes our CI slower. This commit removes the step for storing the binary artifacts to speed up our CI.
=> Remove cloudbuild artifacts

Makefile, install/helm/open-match/values.yaml
We don't officially support tracing yet so disable Jaeger for now in the deployment configs.
=> Disable Jaeger in the Deployment, it'll be enabled in 0.7.0. (#672)

Makefile
This is part of the larger goal of simplifying and speeding up builds.
General strategy here:
1. Add make build/cmd target, to build what is currently in /cmd. <- this PR
2. In the basebuild Dockerfile, run make build/cmd, and replace the seperate Dockerfiles for the services in cmd/ with one Dockerfile (with an arg for which service) which copies from build/cmd/<servicename>/ to the Dockerfile and runs it.
3. Reconcile the Docker images not included in the /cmd to follow this pattern as well (in individual PRs.)
4. Clean up redundant ways to build things.
5. (If it improves speed) add local build variation for faster builds.
=> Add build/cmd to Makefile

internal/app/synchronizer/state.go, internal/app/synchronizer/synchronizer.go, internal/app/synchronizer/synchronizer_service.go
This is in preparation for multi-tenancy as there can be multiple states.
* `sychronizerState` has been renamed to `synchronizerStatus`
* The new `synchronizerState` is basically all the variables of `synchronizerService` broken out into its own class.
=> Breakout synchronizer state into it's own struct.

internal/rpc/clients.go, internal/rpc/server.go, internal/testing/e2e/cluster.go, internal/testing/e2e/common.go, internal/testing/e2e/in_memory.go
```yaml
logging:
rpc: true
```
will now enable HTTP client logging.
Also there's now `--test_only_rpc_logging=true` and `--test_only_metrics=true` for running tests with these options enabled.
=> Add HTTP client logging support and flags for test.

internal/app/backend/backend_service_test.go, internal/app/frontend/frontend_service_test.go, internal/app/mmlogic/mmlogic_service_test.go, internal/app/synchronizer/synchronizer_service_test.go, internal/rpc/clients_test.go, internal/rpc/insecure_test.go, internal/rpc/server_test.go, internal/rpc/tls_server_test.go, internal/statestore/redis_test.go, internal/telemetry/metrics_test.go, internal/util/testing/context.go, test/e2e/fetch_matches_test.go, test/e2e/match_test.go, test/e2e/minimatch_test.go, test/e2e/query_tickets_test.go, test/e2e/ticket_test.go
Calls to Open Match may have HTTP headers or gRPC metadata now and for that to work each test will produce randomized headers to confirm that calls are made appropriately.
=> Replace context.Background() in tests to prepare for multi-tenancy.

install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/values.yaml
The change allows Kubernetes to autoscale Open Match services up to 10 replicas.
=> Add HorizontalPodAutoscaler policies.

cloudbuild.yaml
`Install Kubernetes Toolchain` is now a subset of `Install Toolchain`and should be removed from cloudbuild to save CI time.
=> Remove duplicate step from cloudbuild

Makefile, cloudbuild.yaml, go.mod, tools/reaper/internal/internal.go, tools/reaper/internal/internal_test.go, tools/reaper/reaper.go
This commit together with #701 removes the `Test: Create Cluster` step from cloudbuild to speed up CI. ci-reaper is now responsible for deleting staled namespaces to make sure resources in a broken build will be freed
=> Refactor ci-reap-cluster to ci-reap-namespaces

cloudbuild.yaml
Image artifacts are already pushed to gcr repository in the `Build: Docker Images` step. There is no need to push it twice.
=> Remove image artifacts from cloudbuild

Makefile, cloudbuild.yaml, internal/testing/e2e/cluster.go, tools/reaper/internal/internal.go
This commit does the following things:
1. Fixed the selectors in `make proxy-xxx` commands
2. Fixed the hostname of the match function defined in `internal/testing/e2e/cluster.go` file
3. `make install-ci-chart` does not support end to end test with matchfunction and evaluator yet so disable the customize components for now
4. Let CI pushes the base-build image to the gcr repo since the in-cluster end-to-end test needs contexts in that image to run.
=> Makefile bug fixes

Makefile, cloudbuild.yaml
This is the workaround for #710, line 147 in the Makefile also gives an unique release name to the chart per CI run. It also distinguish the concept of `RELEASE_NAME` and `CHART_NAME` in our Makefile.
`RELEASE_NAME`: The name of the helm release
`CHART_NAME`: The relative path where we store the helm charts
=> Distinguish RELEASE_NAME and CHART_NAME in Makefile

Makefile, cloudbuild.yaml
This commit cleans up the Makefile and removes some duplicated dependencies from cloudbuild to speed up CI.
=> Remove unnecessary dependencies to speed up CI

cloudbuild.yaml
`make assets` requires the tar charts to run its `make install/yaml/` subcommand. This commit let cloudbuild wait for chart binaries to be generated in the `Build: Deployment Configs` step to proceed `make assets`
=> Fix cloudbuild dependency

.golangci.yaml, Makefile
Encountered a bug in golangci. I tried to revert changes file by file yet it is still unclear what is the reason. This commit suppresses the error from golangci in the Makefile to keep it from failing the CI. Golangci cli check is not crital as long as we have its log and the golangci bot so I prefer to suppress its error.
https://pantheon.corp.google.com/cloud-build/builds/628447a1-0601-4e4e-abbd-51fadfff70ec?project=open-match-build
https://github.com/golangci/golangci-lint/issues/484
=> Suppress golangci error

.golangci.yaml
The exclusions list is ever growing because there are many valid
use cases for global variables.  The standard library uses them
all over the place.  Removing the check, and instead relying on
code review to spot bad uses of globals.
=> Ignore globals when linting everywhere.

go.mod, go.sum, internal/app/frontend/frontend_service.go, internal/statestore/redis.go
`gogo/protobuf` library has some subtle bugs that keeps us from adding HTTP support to the MMF and evaluator. This commit replace dependencies on `gogo/protobuf` library with `golang/protobuf` and runs `make sync-deps` to cleanup the `go.mod` file.
=> Remove dependency on gogo/protobuf library

go.mod, go.sum, internal/app/backend/backend_service_test.go, internal/app/mmlogic/mmlogic_service.go, internal/app/mmlogic/mmlogic_service_test.go, internal/statestore/instrumented.go, internal/statestore/public.go, internal/statestore/redis.go, internal/statestore/redis_test.go
Part of the work for https://github.com/googleforgames/open-match/issues/681
This changes the API of FilterTickets to take a pool instead of filter list.  Following the API
in the proposal, different filter types will be different fields on the Pool message.
=> Have filter tickets take pool instead of list of filters

internal/app/synchronizer/state.go, internal/app/synchronizer/synchronizer_service.go
Resolves #763. It seems like sychronizer does respect the config changes. This commit also reduce the log spamming in the synchronizer - Psyonix has thousands of proposals being evaluated per evaluation cycle so logging in terms of proposalIds isn't really useful
To verify - with the following logging changes:
1. Deployed Open Match
2. Edit `synchronizer.registrationIntervalMs` in om-configmap.yaml, run `helm template --namespace open-match install/helm/open-match/ -x templates/om-configmap.yaml | kubectl apply -f -`
3. The new config value shows up when running `kubectl logs -n open-match svc/om-synchronizer`
=> Improve synchronizer logging

internal/statestore/redis.go, internal/statestore/redis_indices.go, internal/statestore/redis_indices_test.go, internal/statestore/redis_test.go
This has two primary advantages:
The redis key of the index can be decided at ticket index / query time.  This is important for string equal indexing, where the plan is to concatenate the OM index name and the string value to form the redis key.
Improved correctness when indexes are changed:  The ticket will now clean up the indexes it was created with, preventing old indices from existing after all the tickets that used them are gone.
This does add an extra read when deindexing a ticket, but I think the correctness improvement alone is worth that.
Other notes:
Turns out the indexes need to be in a list of interface{} to concatenate with the redis key for the cache, so I changed my mind about computing the list in extractIndexedFields.  So extractIndexedFields instead just returns the map …
=> Store indexes used for a ticket, and use them to deindex

.dockerignore, .gitignore, Makefile, cmd/scale-backend/main.go, cmd/scale-frontend/main.go, examples/functions/golang/rosterbased/Dockerfile, examples/functions/golang/rosterbased/main.go, examples/functions/golang/rosterbased/mmf/matchfunction.go, examples/scale/backend/backend.go, examples/scale/frontend/frontend.go, examples/scale/profiles/greedy.go, examples/scale/profiles/multifilter.go, examples/scale/profiles/multipool.go, examples/scale/profiles/profiles.go, examples/scale/tickets/tickets.go, install/helm/open-match/subcharts/open-match-scale/Chart.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-backend.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-configmap.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-frontend.yaml, install/helm/open-match/subcharts/open-match-scale/values.yaml, install/helm/open-match/values.yaml, third_party/protoc-gen-swagger/options/openapiv2.proto
This PR only adds the placeholders for core components and libraries for scale testing Open Match. Subsequent PRs will add implementation for each component.
=> Add placeholder components for Open Match scale benchmarking

go.mod, install/helm/open-match/templates/om-configmap.yaml
This gives the backend sufficient time to allocate DGS.
=> Bump default ignore list ttl to 60 seconds.

Makefile
Upgrade GKE version to 1.13.9-gke.3 since 1.13.6 is no longer available for upgrades and new clusters.
=> Fix create-gke-cluster command

examples/demo/components/clients/clients.go, examples/demo/components/director/director.go
This was possible since the move to read all tickets with no filters.  It simplifies the demo
complexity a bit.
Tangential, but useful to moving to the new API proposal: #765
=> Remove unnecesssary properties and filters in demo

Dockerfile.base-build, Dockerfile.ci, go.mod
I had a problem just now where my local go test would pass, but docker files would fail to build.  My system had an old version of golang:latest cached, which failed to build properly due to missing a new method.  So instead pin the dockerfile to a specific verison.  This way builds will be more deterministic: If a new version of Go comes out, the new features won't work for anyone until this is updated, at which point everyone's local cache will be invalidated.
=> Pin Dockerfile base-build to go version 1.13.1.

install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/om-configmap.yaml, install/helm/open-match/values.yaml
This commit:
1. Changed the maxReplica setting in HorizontalAutoScaler to 30. Otherwise even if we manually override the deployment replica, the actual pod number would still be capped at 10.
2. Changed the swaggerui replica to 1. We don't really need 3 replicas for the swaggerui service.
3. Specified Redis slaveCount explicitly and increase `somaxconn` in host kernel settings when initializing Redis.
4. Increased the max number of Redis idle connections to 5000 so that the redigo pool could reuse more existing idle connections.
=>  Configure Open Match to improve scaling

Makefile, install/helm/open-match/templates/service-account.yaml
Auto-create open-match namespace when open-match-core is enabled. This can slightly improve the user experience by `kubectl apply -f 01-open-match-core.yaml -n open-match` directly without having to manually create the namespace.
=> Added open-match namespace in yaml installation files 

tutorials/director/README.md, tutorials/director/om-director.yaml, tutorials/evaluator/README.md, tutorials/evaluator/om-evaluator.yaml, tutorials/gamefrontend/README.md, tutorials/gamefrontend/om-game-frontend.yaml, tutorials/k8s-resources/matchmaker.yaml, tutorials/matchfunction/README.md, tutorials/matchfunction/om-function.yaml
This commit allows users to copy/paste the commands in the README to build, push, and deploy Open Match tutorial examples.
=> Update tutorial READMEs with more concrete steps

install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml, install/helm/open-match/subcharts/open-match-demo/templates/demo.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-backend.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-frontend.yaml, install/helm/open-match/subcharts/open-match-test/templates/stress-master.yaml, install/helm/open-match/subcharts/open-match-test/templates/stress-slaves.yaml, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/templates/podsecuritypolicy.yaml, install/helm/open-match/templates/swaggerui.yaml, install/helm/open-match/templates/synchronizer.yaml
The k8s v1.16 release will stop serving the some deprecated API versions in favor of newer and more stable API versions, this commit: 
Migrate PodSecurityPolicy to use the policy/v1beta1 API, available since v1.10.
Migrate Deployment to use the apps/v1 API, available since v1.9.
=> Update resource yamls to use k8s v1.16 API

install/helm/open-match/subcharts/open-match-test/templates/e2e-job.yaml, install/helm/open-match/templates/podsecuritypolicy.yaml, install/helm/open-match/templates/service-account.yaml, install/helm/open-match/values.yaml
THP could lead to potential memory leaks and introduce extra query latency to Redis.
This commit aims to disable Transparent Huge Pages (THP) support on the node that is running Redis. 
This requires having a privileged initContainer to access the `/sys` directory in the node. Our current PodSecurityPolicy doesn't allow creating privileged pods so I created a new PSP along with the role bindings just for Redis.
=> Create a privileged service account for Redis and disable THP

install/helm/open-match/subcharts/open-match-test/templates/e2e-job.yaml, install/helm/open-match/templates/service-account.yaml
Generally speaking it is a bad practice to include selector for a k8s pod and helm3 will perform a lint check against this rule. This commit removes selector for the job definition and move the comment of the namespace definition to a more appropriate scope.
=> Update helm templates to follow k8s spec rules

install/helm/open-match/subcharts/open-match-customize/values.yaml, install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/values.yaml, internal/config/config.go, internal/config/config_test.go
This commit is the first step of the Open Match config changes. The goal of the config change is to provide a wrapper for Open Match users such that they don't need to start from a verbose config file to draft their OM settings. The internal config library now requires having a `/app/config/default/matchmaker_config_default.yaml` and `/app/config/override/matchmaker_config_override.yaml` to startup. It will first read from the default yaml, use it's bindings as the default variables and applies the overrides to the config.
=> Config change first step

internal/config/config.go
This change gives Open Match deterministic runtime behavior even if someone changed the `WORKDIR` path in our Dockerfile.
=> Have internal/config/config.go read in file through absolute path

Makefile, cloudbuild.yaml, install/helm/open-match/templates/om-configmap-override.yaml
This commit removed the override-configmap from `01-open-match-core.yaml` and had `make install/yaml` step generate a new yaml template solely for the override configmap.
Resolves #680
=> Split up override configmap from open-match-core static yaml

.dockerignore, .gitignore, Makefile, cloudbuild.yaml
This commit upgraded helm version to helm3-beta.5. It got rid of the `push-helm` and `push-helm-ci` target in the Makefile and cloudbuild.
Also resolves #710
=> Upgrade to helm3

Makefile
#916 introduces a new behavior to our Makefile. Simply running `make install-xx-chart` will now be blocked because of om core services couldn't find the override yaml file. This PR added the override flag to all `make install-xx-chart` commands to simplify the developer experience.
=> Install override yaml file by default when using helm upgrade

install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/values.yaml, internal/telemetry/public.go, internal/telemetry/stackdriver.go
This commit renames `bindStackdriver` to `bindStackdriverMetrics` and turn off stackdriver integration by default. It also change the config names accordingly in `value.yaml` file. Previous comments about the stackdriver integration is off. What we defined in Open Match wouldn't affect the actual logging behavior in GKE, disabling it only affects the stackdriver's metrics/tracing functionalities.
=> Remane bindStackdriver to bindStackdriverMetrics

Makefile, install/helm/open-match/templates/podsecuritypolicy.yaml
When `helm upgrade` failed, helm won't clean up all of the deployed resources properly. The resources mentioned above which are not namespace scoped will be leaked and prevent us from running `install-chart` again. This commit added a `kubectl delete` operation in `make delete-chart` to force delete the PodSecurityPolicy, ClusterRole, and ClusterRolebindings from the cluster.
Also fixed a Makefile target when deploying scale chart.
=> Optimize deployment workflow

install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml
After the harness rewrite in v0.8, we decides to stop using the internal server package for the MMF and Evaluator harness. Since the new serve function under `examples/functions/rosterbased/mmf/server.go` does not contain health check handler anymore, I started to seeing it falls into CrashLoopBackOff status because of the registered k8s probes. This commit removed the k8s probes until we come up with a better story for the harness.
=> Remove k8s probes in example mmfs and evaluator

install/helm/open-match/subcharts/open-match-scale/templates/scale-configmap.yaml, install/helm/open-match/subcharts/open-match-scale/values.yaml
This commit updated the scale test helm chart to make it align with the latest config changes.
=> Fix scale test based on the config changes

Makefile, go.mod, install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml, install/helm/open-match/subcharts/open-match-customize/values.yaml
This commit is part of the user experience Getting Started change, it splits out MMF and Evaluator from open-match-demo installation so that users can see Open Match up and running with the default evaluator when they worked through the Installation steps.
The next step is to migrate the Open Match Demo resources to a different namespace other than Open Match so that users are able to `kubectl delete namespace open-match-demo` and reuse Open Match core services for the tutorials.
=> Split out MMF and Evaluator install from open-match-demo

tutorials/matchmaker101/customization.yaml, tutorials/matchmaker101/matchmaker.yaml
The customization.yaml is now optional when using default evaluator installation steps. Hence we move the match function deployment to matchmaker.yaml
=> Move Match Function installation to the matchmaker.yaml

Makefile, examples/demo/components/director/director.go, install/helm/open-match/subcharts/open-match-demo/templates/demo-podsecuritypolicy.yaml, install/helm/open-match/subcharts/open-match-demo/templates/demo-role.yaml, install/helm/open-match/subcharts/open-match-demo/templates/demo-rolebinding.yaml, install/helm/open-match/subcharts/open-match-demo/templates/demo-serviceaccount.yaml
This commit created a new Makefile target `install-demo` for the demo used in the getting started step and modified the existing Makefile targets to incorporate this change. It also defined the RBAC rules that are necessary to create resources under the `open-match-demo` namespace.
The demo will be broken until we check in the next PR.
=> Define Makefile and RBAC rules for open-match-demo namespace migration

Makefile, install/helm/open-match/subcharts/open-match-customize/templates/customize-configmap.yaml, install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml, install/helm/open-match/subcharts/open-match-customize/values.yaml, install/helm/open-match/subcharts/open-match-demo/values.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-backend.yaml, install/helm/open-match/subcharts/open-match-scale/templates/scale-frontend.yaml, install/helm/open-match/subcharts/open-match-scale/values.yaml, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/mmlogic.yaml, install/helm/open-match/templates/swaggerui.yaml, install/helm/open-match/templates/synchronizer.yaml, install/helm/open-match/values.yaml
This commit completely decouple the customize chart from using the default configmap in `open-match` namespace. As a workaround, it defines a `default` and `override` yaml in the same configmap and mount it to two different volumes - which is required by the harness.
`make install-chart` will now install a demo chart with its MMF to the `open-match-demo` namespace and `open-match-core` to `open-match` namespace.
=> Have MMF and Evaluator in customize chart use different configs

go.sum, internal/rpc/clients.go, internal/rpc/server.go
This commit did a bunch of changes to our `internal/rpc` library:
- Removed the gRPC retry middleware - gRPC retry is only valid for unary service and server stream service. Some of the Open Match services are using client side streaming/bidirectional streaming calls and will be auto failed by the middleware if turned on.
- Added `grpc_tracing` middleware to help context propagation. According to the [doc](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/tracing/opentracing/doc.go), for a service that sends out requests and receives requests, you *need* to use both, otherwise downstream requests will not have the appropriate requests propagated.
- Moved the KeepAliveParams from server side to client side - adding server side keepalive logics without proper configuration on …
=> Update gRPC middlewares used in the internal/rpc library

tutorials/custom_evaluator/director/README.md, tutorials/custom_evaluator/evaluator/README.md, tutorials/custom_evaluator/frontend/README.md, tutorials/custom_evaluator/matchfunction/README.md, tutorials/default_evaluator/director/README.md, tutorials/default_evaluator/frontend/README.md, tutorials/default_evaluator/matchfunction/README.md, tutorials/matchmaker101/director/README.md, tutorials/matchmaker101/frontend/README.md, tutorials/matchmaker101/frontend/ticket.go, tutorials/matchmaker101/matchfunction/README.md, tutorials/matchmaker101/matchfunction/mmf/matchfunction.go, tutorials/matchmaker101/matchmaker.yaml, tutorials/matchmaker102/director/README.md, tutorials/matchmaker102/frontend/README.md, tutorials/matchmaker102/matchfunction/README.md
This commit:
- Improved README instructions for Minikube users.
- Added the matchfunction Service and Pod template to `tutorials/matchmaker101/matchmaker.yaml` to keep it in sync with the solution.
- Added a few commented sections to the template codes to explain what libraries/const we expects users to import when walking through the tutorial
=> Improve README instructions and code templates for the tutorials

tutorials/custom_evaluator/director/README.md, tutorials/custom_evaluator/evaluator/README.md, tutorials/custom_evaluator/frontend/README.md, tutorials/custom_evaluator/matchfunction/README.md, tutorials/default_evaluator/director/README.md, tutorials/default_evaluator/frontend/README.md, tutorials/default_evaluator/matchfunction/README.md, tutorials/matchmaker101/director/README.md, tutorials/matchmaker101/frontend/README.md, tutorials/matchmaker101/frontend/ticket.go, tutorials/matchmaker101/matchfunction/README.md, tutorials/matchmaker101/matchfunction/mmf/matchfunction.go, tutorials/matchmaker101/matchmaker.yaml, tutorials/matchmaker102/director/README.md, tutorials/matchmaker102/frontend/README.md, tutorials/matchmaker102/matchfunction/README.md
Cherry-pick the tutorial changes to 0.8 branch. Per discussion, there is no need for a hot-fix release since this commit only affects the tutorial directory.
=> Improve README instructions and code templates for the tutorials (#997)

Makefile, examples/functions/golang/rosterbased/mmf/server.go, internal/rpc/server.go, internal/testing/e2e/cluster.go, internal/testing/e2e/common.go, internal/testing/e2e/in_memory.go, pkg/harness/function/golang/matchfunction_service.go, test/e2e/game_flow_test.go
This commit does the following things:
1. Explicitly enabled the `dns` resolver in the in-cluster end-to-end test to make sure the load balancer works as expected.
2. Reduced test flakiness by setting `keepalive.EnforcementPolicy` with `PermitWithoutStream` to `true` to match the option set on the client side. Otherwise, if we turn on the grpc logger `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info`, we will see the bidirectional stream server sending `GOAWAY, received too many pings` or `ENHANCE_YOUR_CALM` signal to the clients that has KeepAlive enabled under the hood.
3. Added a `grpc.WaitForReady(true)` call option to each of our end-to-end test calls. We decoupled our MMF from the internal library in v0.8 - which removed the healthcheck handler and k8s readiness probes …
=> Reduced in-cluster test flakiness and stablize gRPC client connections

install/terraform/open-match-build/open-match-build.tf, install/terraform/open-match-build/versions.tf, install/terraform/open-match/secure-gke.tf, install/terraform/open-match/versions.tf
Google recently updated its terraform provider version to 3.0 and it involves a bunch of incompatible changes which blocks the CI - since the CI is using the latest version by default. This commit added a `versions.tf` file and defined the google provider version to 2.8 to unblock the CI.
The rest of the changes are reformat/syntax updates.
=> Fixed terraform google provider version to 2.9

Makefile, install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml, install/helm/open-match/subcharts/open-match-scale/values.yaml, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/om-configmap-default.yaml, install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/values.yaml
This commit fixed an issue where Open Match may throw out `Err: max clients reached` errors from Redis side under load testing scenarios. At this point, Open Match should be able to scale with 1600 profiles and 5000 tickets in the statestore.
The reason that we got those errors from Redis is by default Redis set its `maxClient` connections limit to 10k. However, Open Match has `maxIdle` number set to 5000 per pod, which exceed Redis's limit and failed the API calls. This commit manually overrides the maxClient number to 100k, reduce the maxIdle number to 200, and configure the file descriptors' limit to 10k by setting `sysctl -w net.core.somaxconn=100000` using the initContainer if enabled.
=> Fix Redis Err: Max Clients Reached error

internal/app/backend/backend.go, internal/app/backend/synchronizer_client.go
This also aligns better with patterns for other clients, and removes some synchronization complexity for this type.
=> Have synchronizerClient use cacher, to update on config changes

docs/development.md
One of the first things I wanted to review when cloning the open-match repo was the `install/yaml/01-open-match-core.yaml` file referenced in the documentation which I quickly discovered is generated via helm.
My first attempts to generate it with `make install/yaml/01-open-match-core.yaml` failed and after digging further I realised that helm needed to be configured with a repo to fetch dependencies from via `make update-chart-deps` and then discovered there is an `install/yaml/` target (with the trailing slash to avoid conflicting with the direcory name) that in turn depends on `update-chart-deps` and generates all the .yaml files I was interested in.
I've just added a mention of this to `docs/development.md` in case someone else might benefit from the sign posting.
=> Show how to generate install/yaml files in dev guide

cmd/backend/backend.go, cmd/frontend/frontend.go, cmd/minimatch/main.go, cmd/mmlogic/mmlogic.go, cmd/synchronizer/synchronizer.go, internal/app/appmain.go, pkg/harness/evaluator/golang/harness.go, pkg/harness/function/golang/harness.go
Per discussion, we will have an evaluator and mmf live under the `internal/testing` or `test/e2e` folder for testing purpose. Therefore, it make sense for these components to reuse the internal library instead of reinventing the wheels.
However, the internal config library requires its consumers read in two different config files from different location which complicated the evaluator and mmf setup.
This commit changed the `app.RunApplication` interface to read configurations from a custom getConfig function, such that the new evaluator and mmf could fake their configs and decouple themselves from the internal config library.
=> Have applications read in config from custom input

cmd/scale-evaluator/main.go, cmd/scale-mmf/main.go, examples/scale/evaluator/evaluator.go, examples/scale/mmf/mmf.go, examples/scale/scenarios/basic_scenario.go, examples/scale/scenarios/scenarios.go, internal/util/testing/grpc_options.go
This PR implemented a prototype for Open Match benchmarking framework. The new framework allows users to modify the test behavior via changing the `ActiveScenario` variable under the `open-match/examples/scale/scenarios/scenarios.go` file. Users may choose to implement their own MMF and Evaluator logic for the benchmark by creating a new scenario.
TODOs:
1. Migrate the existing scale package to use this prototypes.
2. Implement actual logics to control the commented parameters.
=> Implement a prototype for Open Match benchmarking framework

Makefile, install/helm/open-match/values.yaml, internal/statestore/redis.go
Resolves #1032.
This commit set the MaxActive number on Redis healthcheck pool to 0 such that the pool does not need to wait for an idle connection while there is no connections available for healthcheck pings. Also increased the MaxIdle and IdleTimeout number to make the pods have a higher chance to pass the readiness health check.
This is an attempt to stabilize the open-match core pods during the CI end-to-end stage to avoid test flakiness.
=> Increase Redis ping time tolerance and provision more resources for CI

examples/scale/backend/backend.go
Start 30 go routines for each at the beginning of the test, and pass them from fetch matches with a buffer.
Gets the redis state store first match to handle >500 tickets per second: 
https://snapshot.raintank.io/dashboard/snapshot/yO88xrIUe1bFR29iNZt4YuM0xuBb8PX9
=> Run scale test assignment and deletes in parallel

api/backend.swagger.json, api/matchfunction.swagger.json, api/messages.proto, api/query.swagger.json, pkg/pb/messages.pb.go
Instead, this is actually just relying on the proto's default values of 0 for each.  As such it shouldn't be documented.
=> Remove inaccurate default documentation on range filter

internal/app/backend/backend_service.go, internal/app/synchronizer/synchronizer_service.go
This is an intermediate step to resolve #939. Leaving a bunch of TODOs in this PR and will fix them after the proto change.
=> Added sync.Map to backend and synchronizer

examples/scale/scenarios/util.go, internal/rpc/server.go
It was previously not reusing it, so the clients would leak over time.
=> Reuse query client in scale tests

cloudbuild.yaml
Kaniko cache introduced some level of flakyness and stucked our CI pipeline for half an hour during the release process. This commit disabled Kaniko cache in cloud build and use the regular Docker builder instead.
```
Fetching storage object: gs://205790239254.cloudbuild-source.googleusercontent.com/c6749c52bd6972ab7b525f1e344998463c560707-a4092d18-2639-4221-944e-95a110ca5233.tar.gz#1580781344938232
Copying gs://205790239254.cloudbuild-source.googleusercontent.com/c6749c52bd6972ab7b525f1e344998463c560707-a4092d18-2639-4221-944e-95a110ca5233.tar.gz#1580781344938232...
/ [0 files][    0.0 B/  3.1 MiB]                                                
/ [1 files][  3.1 MiB/  3.1 MiB]                                                
Operation completed over 1 objects/3.1 MiB. …
```
=> Disabled cloudbuild cacher to avoid build flakyness

cloudbuild.yaml, install/helm/open-match/subcharts/open-match-telemetry/dashboards/grpc.json, install/helm/open-match/subcharts/open-match-telemetry/dashboards/redis.json
This commit:
1. Added an aggregated metric for the Redis dashboard to see the total number of processed commands per instance. Also reworked the CPU usage chart for Redis - This could help us to identify whether Redis is hitting its bottleneck under load - e.g. https://snapshot.raintank.io/dashboard/snapshot/IDKoZqYacXMYcECikPgK9GYJPTn10kEu is showing Redis master is using 1 core - fully loaded and the number of commands processed per second is not increasing anymore starting from 14:05 though I scaled the CreateTicketQPS from 3000 to 4000 afterward.
2. Renamed the gRPC panel rows to most up-to-date API surface names.
=> Update Grafana dashboard for more detailed metrics

internal/statestore/redis.go
As https://snapshot.raintank.io/dashboard/snapshot/IDKoZqYacXMYcECikPgK9GYJPTn10kEu pointed out, 20% of the Redis commands are spent on doing Ping checks when being returned to the pool. This commit checks if this connection have been returned for more than 10 seconds, and only do a PING check if so.
Performance improvement after this change comparing to our current benchmark result at 3k CreateTicketQPS.
https://snapshot.raintank.io/dashboard/snapshot/Wr3lY7TlRN6NIQbF1eOdd1EBNiijKA5f
=> Reduced Redis PING check frequency on Redis pool

Makefile, install/helm/open-match/Chart.yaml
Also fixed a config discrepancy between our Makefile overrides and chart deployment condition. Changed config from `condition: open-match-core.redis.install` to `condition: open-match-core.redis.enabled`。
Resolve #1087
=> Disabled redis when generating static yaml resources except core

internal/filter/filter.go, internal/filter/filter_test.go, internal/filter/testcases/testcases.go, internal/statestore/redis_indices.go, test/e2e/query_tickets_test.go
Adding a filter package which will be used by the query cache to determine if a filter is within a given pool.
This comes with a suite of test cases which test individual tickets against a pool for fine grained testing.
Split the tests in query_tickets_test to handle a few special case tests more simply or thoroughly, and then use the above test cases for everything else.
This methodology found one bug with the redis implementation, where a max value on a double filter of NaN wouldn't properly exclude all tickets.  As such, added a special case for it.  (not that it will live long anyways, but it was any easy fix.)
=> Add filter package, and rework query testing

internal/statestore/redis.go, test/e2e/game_flow_test.go, test/e2e/minimatch_test.go, test/matchfunction/mmf/matchfunction.go
This prevents clients from unintentionally depending on the return order of tickets.
This is currently happening with our tests, so this includes several fixes for the tests.
=> Do some randomization on return order of tickets

install/helm/open-match/templates/swaggerui.yaml, install/helm/open-match/values-production.yaml, install/helm/open-match/values.yaml
This commit added the ability to control the installation of swaggerui via helm. The basic `values.yaml` file has swaggerui enabled by default while the production one has it disabled.
Resolved #1140
=> Disable swaggerui installation via helm

install/02-open-match-demo.yaml
As Paul pointed out in #1145, there are two unused legacy volume mounts in our `02-open-match-demo.yaml` file. These two mounts were used in our om-function and director deployments to connect to the query service and backend back in v0.8 but should be removed along with the other internal references when we deprecated the usage of harnesses.
=> Removed legacy volume mounts from om-demo yaml file

install/helm/open-match/templates/om-configmap-default.yaml, internal/statestore/redis.go, internal/statestore/redis_test.go
Resolved #815.
Per discussion, removed the `EXPIRE` logic from our statestore implementation.
=> Removed ticket auto-expiring logic from statestore

go.sum, third_party/google/api/resource.proto, third_party/google/rpc/code.proto, third_party/google/rpc/error_details.proto, third_party/google/rpc/status.proto
This pulls in changes from running presubmit, so they're separate from a logical change.
See https://github.com/googleforgames/open-match/issues/1132
=> update third party files

internal/app/frontend/frontend_service.go, test/e2e/ticket_test.go
Resolves #1033
- Add the check to frontend_service.
- Add test coverage for this check and for another pre-existing (but untested) check.
- Remove an unused assignment from a different test, as it's no longer valid.
=> forbid assignment on ticket create

api/frontend.proto, api/frontend.swagger.json, examples/demo/components/clients/clients.go, examples/scale/frontend/frontend.go, internal/app/frontend/frontend_service.go, internal/app/frontend/frontend_service_test.go, internal/testing/fake_frontend.go, pkg/pb/frontend.pb.go, pkg/pb/frontend.pb.gw.go, test/e2e/game_flow_test.go, test/e2e/minimatch_test.go, test/e2e/query_tickets_test.go, test/e2e/ticket_test.go
Follows the guide here: https://cloud.google.com/apis/design/standard_methods
Create/Get return the resource directly.
Delete returns empty.
GetAssignments changes to WatchAssignments, because it's not a get call but instead a streaming response.
=> Better follow API guidelines

cmd/default-evaluator/main.go, internal/app/evaluator/evaluator.go, internal/testing/e2e/in_memory.go, internal/testing/mmf/matchfunction.go, internal/testing/mmf/matchfunction_service.go, test/matchfunction/main.go
This brings the test mmf and standard evaluator closer to the other commands.  So now they read the config instead of hardcoding it, and they use a bind function (though it's customized with the actual mmf or evaluator code.)
Also a small extra empty line to separate out license because it's not godoc.
=> Use consistent main code for mmf and evaluator

internal/appmain/appmain.go, internal/rpc/insecure.go, internal/rpc/server.go, internal/rpc/tls_server.go
When debugging, I saw that this would always log an useless error.  This is because both grpc and http servers will always close their listener when they themselves close.  As such, this statement always logs that it can't use a closed listener, even when it's trying to close the listener.
Also moved from logging the error to returning it, so that errors with closing are more noticeable.
=> Remove errant closing of already closed listeners

Makefile, docs/governance/templates/release.sh
With this change, there is one source of truth, so things won't get out of sync.
Also removed the "copy to release notes" note, because we're not doing that anymore.
=> fix release.sh not knowing the right images

internal/statestore/redis_test.go, internal/statestore/testing/fake_redis_test.go
Several fixes in order to avoid nil pointer exceptions in cases if tests fail.
=> Use require in tests to avoid nil pointer exceptions

internal/app/evaluator/defaulteval/evaluator_test.go, internal/app/frontend/frontend_service_test.go, internal/app/query/query_service_test.go
Switched from _require_ to _assert_.
Also made output where we compare error codes more readable.
Current output:
```
Error:      	Not equal: 
expected: 0xa
actual  : 0xe
```
After the fix:
```
Error:      	Not equal: 
expected: "Aborted"
actual  : "NotFound"
```
=> Improved app tests

internal/rpc/server.go, internal/statestore/redis.go, internal/statestore/redis_test.go
Closes #1228 
Previously _context canceled_ message was mentioned twice: 
1) connect method
2) GetAssignments method, after GetTicket returns an error.
Logs before the fix:
I suggest to log everything on a very top level of API and just wrap everything which comes from lower levels.
Also, I've made logs more informative adding an ID to each record.
Logs after the fix:
=> Reduce logging in statestore - redis

examples/functions/golang/soloduel/mmf/matchfunction_test.go, internal/filter/filter_test.go, internal/logging/logging_test.go, internal/rpc/clientcache_test.go, internal/rpc/clients_test.go, internal/rpc/insecure_test.go, internal/rpc/server_test.go, internal/rpc/tls_server_test.go, internal/telemetry/configz_test.go, internal/telemetry/help_test.go, internal/telemetry/probe_test.go, tools/certgen/internal/internal_test.go, tools/certgen/testing/certbundle_test.go
Continue updating tests with switching from _assert_ to _require_.
=> Tests update: use require assertion

cloudbuild.yaml
In order to use the cloud build file on a separate GCP project different infrastructures need to be deployed, including a couple of GS Buckets. Unfortunately, the cloud build file has the open-match build pipeline buckets for artifacts and logs hardcoded and not exposed as substitution variables.
This PR creates two substitution variables for the buckets (`_ARTIFACTS_BUCKET`, and `_LOGS_BUCKET`), allowing a google cloud build to succeed by using a different value for these variables.
=> Replaced GS bucket links with substitution variables

internal/app/backend/backend_service.go, internal/app/evaluator/evaluator_service.go, internal/app/frontend/frontend_service.go, internal/app/frontend/frontend_service_test.go, internal/app/query/query_service.go, internal/rpc/server.go, internal/testing/e2e/ticket_test.go
Added unary interceptor and removed logs from _app_ package. 
Relates to #1102
=> Added unary interceptor and removed extra logs

install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/values.yaml, internal/app/backend/backend_service.go, internal/rpc/clientcache.go, internal/rpc/clientcache_test.go, internal/testing/e2e/common.go, internal/testing/e2e/fetch_matches_test.go
Whenever a profile points to a function that is not available, a call to `FetchMatches` with that profile will force us to wait for the full length of `proposalCollectionInterval` before getting back an error saying that the function took longer than the collection interval to return results. It would be expected that if the function is not available, we should fail fast. This change adds an additional check before calling the function to see if the provided address is available. 
**Which issue(s) this PR fixes**: No issues created for this.
Open to suggestions on a more robust way to do this.
=> Unavailable gRPC match functions forces us to wait the proposalCollectionInterval before failing

install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/values.yaml, internal/app/backend/backend_service.go, internal/rpc/clientcache.go, internal/rpc/clientcache_test.go, internal/testing/e2e/common.go, internal/testing/e2e/fetch_matches_test.go
Reverts googleforgames/open-match#1271 while we figure out how to fix the test, so other PRs aren't blocked.
=> Revert "Unavailable gRPC match functions forces us to wait the proposalCollectionInterval before failing"

internal/app/evaluator/defaulteval/evaluator.go, internal/app/evaluator/defaulteval/evaluator_test.go
PR updates logic of the default evaluator to consider backfill's id when de-colliding matches
=> Consider backfill's id when de-colliding matches

internal/app/frontend/frontend.go, internal/app/frontend/frontend_service.go, internal/app/frontend/frontend_service_test.go, internal/testing/e2e/backfill_test.go
Initial version of CreateBackfill. It stores an empty regular TicketIds list.
Wait on StateStare changes.
=> Frontend Create Backfill

Makefile, internal/app/query/cache.go, internal/app/query/query.go, internal/app/query/query_service.go, internal/statestore/backfill.go, internal/statestore/instrumented.go, internal/statestore/public.go, internal/testing/e2e/common.go, internal/testing/e2e/query_backfills_test.go, pkg/matchfunction/matchfunction.go
PR allows querying and caching backfills.
A take over of #1300 and #1280 also has @Laremere comments.
=> Implement backfill querying

internal/app/backend/backend_service.go, internal/app/frontend/frontend_service.go, internal/statestore/backfill.go, internal/testing/e2e/backfill_test.go, internal/testing/e2e/query_backfills_test.go
Autoincrement Backfill Generation for QueryBackfills and BackfillCache to work as expected.
In order Backfill Cache to work in QueryBackfill, every update should
store a backfill as a new Generation Backfill.
Work on #1294 .
In the future Generation could be renamed to Version field in Backfill,
one change at a time.
=> Backfill: Autoincrement generation on every Backfill update

install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml
Add pod tolerations, nodeSelector and affinity in helm for subcharts
Closes #1015
=> Add pod tolerations, nodeSelector and affinity in helm for subcharts

internal/app/frontend/frontend_service_test.go, internal/statestore/backfill.go, internal/statestore/backfill_test.go, internal/testing/e2e/query_backfills_test.go
Previously it was possible to "resurrect" expired backfills. With this fix, you are not allowed to do that.
=> Expired backfills can not be updated or acknowledged

internal/app/synchronizer/synchronizer_service.go, internal/statestore/backfill.go, internal/statestore/backfill_test.go, internal/testing/e2e/backfill_test.go
During the contributor's meeting, we agreed with @Laremere to follow this pattern in the cleanup backfills process.
Move CleanupBackfills after main SynchronizerCycle. 
There are some benchmarks:
**Using workers pool**
workers=5; expired backfills=50
```BenchmarkCleanupBackfills-12    	      40	  28685354 ns/op	15493765 B/op	   90618 allocs/op```
workers=3; expired backfills=50
```BenchmarkCleanupBackfills-12    	      34	  29910474 ns/op	15493394 B/op	   90614 allocs/op```
workers=1; expired backfills=50
```BenchmarkCleanupBackfills-12    	      26	  40829001 ns/op	15492384 B/op	   90604 allocs/op```
workers=5; expired backfills=200
```BenchmarkCleanupBackfills-12    	       9	 114774808 ns/op	61991684 B/op …
```
=> Move Cleanup Backfills after main SynchronizerCycle & add workers pool

internal/app/backend/backend_service.go, internal/testing/e2e/backfill_test.go, internal/testing/e2e/common.go
There could be the case when backfill returned by the MMF was deleted
in CleanupBackfills.
We need neither return an error if UpdateBackfill failed due to deleted Backfill , nor return the match.
Relates to #1334
=> Backfill: Skip not found errors on Backend

internal/testing/e2e/backfill_test.go
This PR improves tests output in case of a failure.
Before:
```        	Error:      	Not equal:
expected: *errors.errorString(&errors.errorString{s:"EOF"})
actual  : *status.Error(&status.Error{e:(*status.Status)(0xc000b08600)})
```
After:
```
Error:      	Not equal: 
expected: "EOF"
actual  : "qwe"
```
=> Add string err comparisons to backfill e2e

examples/demo/bytesub/bytesub.go, examples/demo/updater/updater.go, examples/functions/golang/backfill/mmf/matchfunction.go, internal/statestore/public.go, pkg/matchfunction/matchfunction.go
There was typos in new Backfill function matchId name.
If we are using two profiles with the same Backfill MatchFunction it would produce same matchIds and generates such error in Synchronizer:
```
"Status": "Encountered error: rpc error: code = Unknown desc = error(s) in FetchMatches call. syncErr=[error receiving match from synchronizer: rpc error: code = Unknown desc = error calling evaluator: multiple match functions used same match_id: \"profile-backfill-matchfunction-time-2021-01-21T17:55:27.65-num-1-c04s\"], mmfErr=[\u003cnil\u003e]",
```
=> Fix minor typos

internal/testing/e2e/fetch_matches_test.go, internal/testing/e2e/query_backfills_test.go, internal/testing/e2e/query_tickets_test.go
This PR fixes an output in tests in case of an error.
Before:
```        	Error:      	Not equal:
expected: *errors.errorString(&errors.errorString{s:"EOF"})
actual  : *status.Error(&status.Error{e:(*status.Status)(0xc000b08600)})
```
After:
```
Error:      	Not equal: 
expected: "EOF"
actual  : "qwe"
```
=> Make tests output readable

internal/statestore/backfill.go, internal/statestore/backfill_test.go, internal/statestore/ticket.go, internal/statestore/ticket_test.go
Delete requests will return 404 instead of 200 when the resource (ticket) is not found. This does not break the concept of idempotency and will align with get requests as well as the frontend swagger configuration.
=> Return 404 when deleting ticket/backfill ticket that does not exist

tutorials/matchmaker101/solution/director/profile.go
The tutorial solution to matchmaker101 director fails to fetch matches:
```shell
2021/04/16 19:14:14 Failed to fetch matches for profile mode_based_profile, got rpc error: code = Unknown desc = error(s) in FetchMatches call. syncErr=[error receiving match from synchronizer: rpc error: code = Unknown desc = error calling evaluator: multiple match functions used same match_id: "profile-mode_based_profile-time-2021-04-16T19:14:14.19-0"], mmfErr=[<nil>]
2021/04/16 19:14:14 Failed to fetch matches for profile mode_based_profile, got rpc error: code = Unknown desc = error(s) in FetchMatches call. syncErr=[error receiving match from synchronizer: rpc error: code = Unknown desc = error calling evaluator: multiple match functions used same match_id: …
```
=> add mode to profile name for range of game modes

install/helm/open-match/subcharts/open-match-scale/templates/scale-frontend.yaml
Recent k8s APIs remove `Deployment` from `extensions/v1beta1`, it's now in `apps/v1`.
Without this update, yaml generated by this template fails with
`no matches for kind "Deployment" in version "extensions/v1beta1"`
=> fix outdated apiVersion in frontend scale testing helm template

install/helm/open-match/values.yaml
I have set resource requests against each component part of Redis and set the 'slaveCount' to 3 (as this actually sets the total number of pods and a minimum of 3 is required for a robust Redis Sentinel deployment, see: https://redis.io/topics/sentinel#fundamental-things-to-know-about-sentinel-before-deploying)
Closes #1428 
Closes #1420 
I installed open match in minikube with these changes and checked logs to make sure all was healthy. I deleted pods and watched the logs to make sure the new nodes synced.
=> Redis default values update

Dockerfile.cmd, Makefile
Reduces docker CMD build times by mounting cache for go dependencies. 
#1227 
Closes #
It requires docker 19.03 version or later which is not very much new (released on 2019-07-22) and latest verision is 20.10 so I hope it works for all.
https://www.docker.com/blog/containerize-your-go-developer-environment-part-1/#:~:text=As%20we%20are,in%20your%20environment.
Reference :- https://www.docker.com/blog/containerize-your-go-developer-environment-part-2/
=> docker build optimization by using mount cache for go dependencies

internal/statestore/ticket.go, internal/statestore/ticket_test.go, internal/testing/e2e/ticket_test.go
**What this PR does / Why we need it**: When making a call to `AssignTicketsRequest`, To check at least one of the `AssignmentGroup` have at least one `ticket_ids` present such that redis command doesn't throw error.
```
time="2020-10-09T12:38:09Z" level=error msg="failed to update assignments" app=openmatch component=app.backend error="ERR wrong number of arguments for 'mget' command"
time="2020-10-09T12:38:09Z" level=error msg="failed to update assignments for requested tickets" app=openmatch component=app.backend error="ERR wrong number of arguments for 'mget' command"
```
To prevent the code execution from going into this situation, we can check the length of the array containing all `ticket_ids`, so that in case `AssignmentGroup` doesn't contain any value in `ticket_ids` will return …
=> AssignTickets empty check and test cases added

Makefile, internal/app/frontend/frontend_service.go
**What this PR does / Why we need it**: This PR modifies the `FrontendService.WatchAssignment` function and listens to the `ctx.Done` functionality of GRPC stream in callback function so that in every retry of callback function, it is checked whether the user has terminated this API call or not.
Closes #1472 
- Updated the GKE version for regular channel support (i.e. 1.22.8-gke.202) [Reference](https://cloud.google.com/kubernetes-engine/docs/release-notes)
=> Update WatchAssignment function

internal/app/query/cache.go, internal/app/query/query.go
* Added metrics for total number of tickets and total number of backfills 
* Fixed totalBackfillTicketsView Name
* Added metric for keeping track of tickets in pending state
* altered name of total tickets to total 'active' tickets to remove confusion
* updated pending tickets metric name
* Register totalActiveTicketsView and pendingTotalTicketsView
Closes #
=> Add metrics (#1491) to main

Makefile, install/helm/open-match/subcharts/open-match-telemetry/dashboards/match-making.json, internal/app/query/cache.go
**What this PR does / Why we need it**: This PR adds the grafana panels under the new row `Ticket Metrics` in `MatchMaking` dashboard to show the new metrics about matchmaking and ticket behaviour.
Closes #1482 
**Special notes for your reviewer**: 
- Updated the selector of grafana service in `proxy-grafana` command of makefile.
- Updated the proxy commands of grafana and prometheus to target service instead of pod to align as per the documentation website.
- Updated the `create-gke-cluster` command in makefile.
=> Ticket metrics panels

install/helm/open-match/subcharts/open-match-customize/templates/evaluator.yaml, install/helm/open-match/subcharts/open-match-customize/templates/matchfunctions.yaml, install/helm/open-match/templates/_helpers.tpl, install/helm/open-match/templates/backend.yaml, install/helm/open-match/templates/frontend.yaml, install/helm/open-match/templates/query.yaml, install/helm/open-match/values-production.yaml, install/helm/open-match/values.yaml
**What this PR does / Why we need it**: This PR implements a feature to provide the functionality of maintaining the HPA for the microservices individually rather than a general config applicable for all microservices so that minimum number of replicas could be set higher than others for the some particular microservice. In the concerned issue mentioned, There is need to keep minimum replicas of query microservice ready to serve.
Closes #1390 
=> Specify HPA for individual service

internal/config/config.go, internal/statestore/backfill.go, internal/statestore/redis.go, internal/statestore/ticket.go
**What this PR does / Why we need it**:  This PR sets the default values of various configs in matchmaker_config_override.yaml file of open-match override configmap to ensure smooth start-up of all deployments in case any config is missing or omitted. Below is the list of default values of respective configs:
- registrationInterval: 1s
- proposalCollectionInterval: 10s
- pendingReleaseTimeout: 1m
- assignedDeleteTimeout: 10m
- queryPageSize: 1000
- backfillLockTimeout: 1m
Closes #1013 
=> Default values of configs

install/helm/open-match/templates/om-configmap-override.yaml, install/helm/open-match/values-production.yaml, install/helm/open-match/values.yaml
Currently, ConfigMap (open-match-override) should be installed via `--set open-match-override.enabled=true`.   
This PR enables users to set `open-match-override.enabled` with `values.yaml`.
Closes #
=> Add open-match-override setting

tutorials/redis-enterprise-cloud/README.md
**What this PR does / Why we need it**: Added instructions to deploy Redis Enterprise for Open Match installation.
**Which issue(s) this PR fixes**: N/A
**Special notes for your reviewer**: None
=> Added Redis Enterprise Deploy Instructions

Makefile, install/helm/open-match/Chart.yaml
**What this PR does / Why we need it**: This PR contains the changes required for update to repo link of Bitnami's helm chart where the redis's archived chart can be fetched. The updated retention policy for bitnami's helm charts keeps the newly published charts for 6 months before moving to archive.
Closes #1523 
=> update helm chart repo link

internal/app/backend/backend_service.go
The HTTP POST request to run the Match Function (`/v1/matchfunction:run`) currently has no `Content-Type` header on it. This prevents parsing utils (such as https://www.npmjs.com/package/body-parser) from automatically being able to parse the JSON body. This PR adds the missing `Content-Type` header as well as the `Transfer-Encoding` header.
There is no associated issue for this.
Here is the Slack conversation about this issue: https://open-match.slack.com/archives/CCD3H0L2D/p1673486707254609
=> Fix: add Content-Type and Transfer-Encoding to matchfunction:run POST request

.github/ISSUE_TEMPLATE/release.md, Makefile, cloudbuild.yaml, install/helm/open-match/Chart.yaml, install/helm/open-match/values.yaml
Update CODEOWNERS by @govargo in https://github.com/googleforgames/open-match/pull/1671
Bumps golang.org/x/net from 0.7.0 to 0.17.0 by @govargo in https://github.com/googleforgames/open-match/pull/1672
Update google.golang.org/grpc from 1.57.0 to 1.57.1 by @kazshinohara in https://github.com/googleforgames/open-match/pull/1673
Tested against Kubernetes Version 1.24 and 1.25
Helm chart tested using Helm Version 3.12.3
Modifying Open Match core requires Golang Version >= v1.21
=> Release 1.8.1

install/helm/README.md
Currently the Cloud Build failed by 404 in link.
```
Issues :-(
> Links 
1. [L08] 404 https://cloud.google.com/stackdriver/  
> Checking links in ./install/helm/open-match/subcharts/open-match-telemetry/dashboards/README.md
```
This build isse blocking #1760 and #1761 
None
=> Fix 404 link for stackdriver
